config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config.py, testsuite/objects/__init__.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/operator/conftest.py
* The operator test will be skipped if that's the case.
* You can set it up by settings `authorino.deploy` to false
* You also need to specify the authorization URL for it through `authorino.url`
* Details can be found in `settings.local.yamp.tpl`
=> Enable running on already deployed Authorino

testsuite/openshift/httpbin.py, testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/conftest.py
Httpbin is now session scope, while envoy is module scoped.
Closes #3 
Breaks #18 and #19 but I will rebase the PRs base on which gets approved first
=> Separate Httpbin and Envoy

testsuite/openshift/objects/auth_config.py, testsuite/openshift/objects/authorino.py, testsuite/tests/kuadrant/authorino/conftest.py
This should ensure that Authorino reconciles only its own AuthConfigs.
Depends on #21
=> Use Label selectors

testsuite/objects/__init__.py, testsuite/openshift/httpbin.py, testsuite/openshift/objects/auth_config.py, testsuite/tests/kuadrant/authorino/identity/rhsso/multiple_hosts/conftest.py, testsuite/tests/kuadrant/authorino/identity/rhsso/multiple_hosts/test_multiple_hosts.py
Simple test for AuthConfig with two hosts
Closes #24
=> Add tests for multiple hosts

Pipfile, README.md, config/settings.local.yaml.tpl, config/settings.yaml, testsuite/certificates/__init__.py, testsuite/httpx/__init__.py, testsuite/openshift/client.py, testsuite/openshift/httpbin.py, testsuite/openshift/objects/authorino.py, testsuite/resources/tls/envoy.yaml, testsuite/resources/tls/intermediate_config.json, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/operator/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/README.md, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/test_tls.py
* Add classes for working with Certificates and CFSSL
* CFSSL is a library developed by Cloudflare to make generating certificates easy (much easier than with regular OpenSSL)
* Add test for Authorino with TLS
* Tests that Authorino and Envoy can be configured with TLS and that they work
* Update README.md to reflect changes
* Fix wrong minimum python version, there should have always been a 3.9
* Add new template for Envoy with TLS
* Ignore too-many-arguments warnings
* Useless warning 
* Change scope fo Authorino fixture to module
* Any module can now make changes to the configuration   
Closes #7
=> Add TLS support

testsuite/openshift/objects/__init__.py, testsuite/openshift/objects/api_key.py, testsuite/openshift/objects/auth_config.py, testsuite/openshift/objects/authorino.py
- Add `@modify` decorator, which ensures the same methods can be used even if the object is already committed to the server.
- Currently, the methods would modify the inner state of the object but wouldn't be propagated to the server. This enables them to modify their inner state before commitment and apply it even when it is already committed.  
- Create parent class for all our APIObjects
=> Add modify decorator

testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py, testsuite/tests/kuadrant/authorino/operator/conftest.py
Previously we had only one label, which lasted the entire test run, meaning different modules could share resources. This eliminates it.
=> Add module_label

testsuite/tests/conftest.py
Before this, it would throw an error due to incorrect usage of pytest.skip (too many arguments)
=> Fix RHSSO error message

pylintrc, testsuite/certificates/__init__.py, testsuite/openshift/client.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/utils.py
* Enables us to create more complex certificate chains
* Certificates are defined as a Dict with a clear hierarchy, so it is easy to see the structure
* Some typing changes in certificates
* Also, some typing ignores in the actual method
* Either mypy is not very clever or my checks are not 100%
=> Introduce cert_builder

testsuite/tests/kuadrant/authorino/identity/rhsso/conftest.py
OIDC auth is automatically configured by conftest authorino contest. Removing redundant fixture
=> Remove redundant auth fixture from RHSSO indentity tests

testsuite/objects/__init__.py, testsuite/openshift/objects/auth_config.py, testsuite/tests/kuadrant/authorino/authorization/test_opa.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/identity/api_key/conftest.py
Depends on https://github.com/Kuadrant/testsuite/pull/45
=> Tests for Open Policy Agent (OPA) Rego policies

testsuite/objects/__init__.py, testsuite/openshift/objects/auth_config.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/identity/api_key/conftest.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/test_all_namespace_api_key.py
These tests contain duplicate code from API key identity match label tests. Once the enhancement described in https://github.com/Kuadrant/testsuite/issues/62 is solved, this duplication can be easily removed and this test will be part of identity/api_key/test_match_labels.py
=> Add cluster-wide API key identity tests

config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config/__init__.py, testsuite/config/openshift_loader.py, testsuite/openshift/client.py, testsuite/tests/conftest.py
Change how the OpenShift is loaded in testsuite, now all the processing (e.g. converting it to OpenShiftClient) occurs in the new dynaconf loader and the respective sections in the testconfig are already processed OpenShiftClients.
Config structure regarding the second OpenShift project was changed.
=> Change how are OpenShifts processed in the settings

testsuite/tests/kuadrant/authorino/operator/test_wildcard.py
It was using static "*.redhat.com" wildcard
=> Fix wildcard

testsuite/openshift/envoy.py, testsuite/openshift/httpbin.py, testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/operator/test_sharding.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py
* All envoy classes are not in one envoy module, instead of httpbin one
* Change naming of envoy instances, previously there was envoy mentioned twice
* Fix route() property of envoy to accurately select route even if it was called after another route was requested
=> Separate envoy into its separate module

testsuite/httpx/auth.py, testsuite/openshift/objects/api_key.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/identity/api_key/conftest.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_match_label.py
Added API key to our openshift object api_key.py that represents Secret in the OCP. 
The benefit is that it is now possible to get the API key directly from the API key secret object: `api_key_secret.api_key`
=> Created API key variable for API key openshift object

testsuite/openshift/objects/api_key.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_reconciliation.py
Last subtask for https://github.com/Kuadrant/testsuite/issues/1
=> Add tests for API key Secret reconciliation

README.md, config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config/__init__.py, testsuite/config/openshift_loader.py, testsuite/config/tools.py
- Lazily loads required info from OpenShift
- For now only loads RHSSO details, if not present
This is an alternative to #71, does the same, from the user perspective works the same but is implemented differently using Validators instead of a loader.
=> Add tools 

testsuite/openshift/objects/__init__.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py, testsuite/tests/kuadrant/conftest.py
- Should leave less trash when authorization.commit fails
- Ignore not found resources when deleting by default
=> Fix AuthConfig cleanup

testsuite/tests/kuadrant/authorino/test_redirect.py
The current version doesn't work because there is no default Auth option which means it doesn't require any authentication, to begin with.
=> Fix redirect test

testsuite/objects/__init__.py, testsuite/openshift/objects/auth_config.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_auth_credentials.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_auth_credentials.py
Add test for RHSSO and API key auth credentials location. Tests are for authorization_header with custom prefix, custom header, query and cookies.
Closes #107
=> Auth credentials

config/settings.yaml, testsuite/openshift/objects/authorino.py, testsuite/tests/kuadrant/authorino/conftest.py
Temporarily adding debug log level for Authorino. 
When we add logs to the test results in the future, we can set this as an optional option for test runs.
=> Added logLevel debug for authorino

testsuite/openshift/objects/__init__.py
Now it has the correct spelling
=> Fix typo in OpenShiftObject.committed

Makefile, pytest.ini, testsuite/openshift/httpbin.py, testsuite/openshift/objects/ingress.py, testsuite/tests/conftest.py, testsuite/tests/glbc/conftest.py, testsuite/tests/glbc/test_ingress_reconciliation.py
closes: https://github.com/Kuadrant/testsuite/issues/23
=> glbc: add simple ingress host field reconciliation test

mypy.ini
* mypy 990 (https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html) make strict optional as default, meaning Types that have default value of None are no longer implicitly Optional
* It is technically forbidden by PEP, but I wont change it now, it is a bigger change and it causes the type to be longer
=> Add implicit_optional to mypy

testsuite/objects/sections.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py
This PR adds testcase for testing k8s Dynamic Admission Control webhooks, see https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/ which are used for calling Authorino service for authenticating of Ingress object creation.
=> Add webhooks test

testsuite/httpx/auth.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_rhsso_roles.py, testsuite/tests/kuadrant/authorino/metadata/test_uma.py, testsuite/tests/kuadrant/authorino/metadata/test_user_info.py
Should help with cases where you have multiple users
=> Add ability to create HttpxOidcClientAuth from User

testsuite/tests/kuadrant/authorino/operator/tls/conftest.py
Correct scopes for the tls conftest, so there is actually an option to overwrite the default certificate hierarchy. Currently, conftest fixtures always return certificates from the first found `certificates` fixture in the testsuite, as they have `session` scope. With new `module` scopes they will return the certificate according to the overwritten fixture (if there is one).
Also, the secret creation scope changed from `session` to `module`, so these secrets aren't left until the end of the testsuite execution.
=> Fix scopes in tls conftest

config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config/__init__.py, testsuite/openshift/client.py, testsuite/openshift/envoy.py, testsuite/openshift/httpbin.py, testsuite/openshift/objects/auth_config/__init__.py, testsuite/openshift/objects/auth_config/auth_policy.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/openshift/objects/gateway_api/__init__.py, testsuite/openshift/objects/proxy.py, testsuite/openshift/objects/route.py, testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/identity/anonymous/test_anonymous_context.py, testsuite/tests/kuadrant/authorino/identity/api_key/conftest.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_auth_credentials.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_auth_credentials.py, testsuite/tests/kuadrant/authorino/metadata/test_uma.py, testsuite/tests/kuadrant/authorino/multiple_hosts/conftest.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py, testsuite/tests/kuadrant/authorino/operator/conftest.py, testsuite/tests/kuadrant/authorino/operator/sharding/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/tests/kuadrant/authorino/response/conftest.py, testsuite/tests/kuadrant/conftest.py
This PR adds the ability to run (most of) the authoring tests on Kuadrant. The actual tests are mostly unchanged, but everything else had to change in some mostly minor ways. Currently, around 43 out of 106 tests run on Kuadrant, and many need code changes that will come in subsequent PRs.
* Add `Route` and `Proxy` interfaces
* Kuadrant uses a different route and differently configured envoy than we do, so I added these interfaces to ensure compatibility with new Kuadrant classes.
* Change some parameter types in said classes to ensure compatibility with the new ones.
* Add `run_on_kuadrant` fixture, which indicates that the test or module doesn't run on Kuadrant
* Add configuration options for Kuadrant deployment
* It expects that Kuadrant and Gateway are already deployed.
=> Add support for Kuadrants AuthPolicy

testsuite/mockserver.py, testsuite/oidc/rhsso/__init__.py, testsuite/oidc/rhsso/objects.py, testsuite/resources/dinosaur_config.yaml, testsuite/tests/kuadrant/authorino/dinosaur/conftest.py, testsuite/tests/kuadrant/authorino/dinosaur/test_auth_config.py
This PR adds tests for complex AuthConfig based on https://github.com/guicassolato/kas-fleet-manager-authorino/blob/main/kas-fleet-manager-authconfig.yaml
#153 needs to be merged first
Resolves #152
=> Add tests for complex AuthConfig

testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/identity/auth/test_auth_identity.py, testsuite/tests/kuadrant/authorino/response/conftest.py, testsuite/tests/kuadrant/conftest.py
Requires #158. Adds `authorization_name` fixture, which enables parametrization of `Authorization` without recreating it.
=> Enable response tests on Kuadrant

testsuite/openshift/objects/auth_config/__init__.py, testsuite/openshift/objects/auth_config/auth_policy.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/test_wildcard_collision.py, testsuite/tests/kuadrant/authorino/operator/test_wildcard.py
Fix to the https://github.com/Kuadrant/testsuite/pull/158. In the AuthConfig instance creation, there was still parsed string instead of the route object or list with hostnames.
=> Fix authconfig instance parameters

testsuite/tests/kuadrant/authorino/dinosaur/conftest.py
AuthConfig is hardcoded there and we do not yet have tooling to set it up from testsuite
=> Ignore dinosaur test on Kuadrant

testsuite/mockserver.py, testsuite/tests/kuadrant/authorino/authorization/opa/external_registry/conftest.py, testsuite/tests/kuadrant/authorino/authorization/opa/external_registry/test_auto_refresh_policy.py, testsuite/tests/kuadrant/authorino/dinosaur/conftest.py, testsuite/tests/kuadrant/authorino/metadata/test_http.py
This PR adds some functionality and simplifies Mockserver
- removes the unnecessary `path` argument for the `create_expectation` method. The `expectation_id` is used to create a path for expectation. It is possible to create expectations with scope function.
- adds a new method that creates an expectation for templated responses: https://www.mock-server.com/mock_server/response_templates.html
- an instance of mockserver now stores live expectations
=> Simplify Mockserver expectation

testsuite/openshift/objects/auth_config/auth_policy.py, testsuite/openshift/objects/gateway_api/__init__.py, testsuite/tests/kuadrant/authorino/multiple_hosts/conftest.py
Requires #158. Adds host manipulation to AuthPolicy in a not-ideal way.
=> Enable multiple_host test on Kuadrant

testsuite/certificates/__init__.py, testsuite/httpx/__init__.py, testsuite/openshift/client.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_attributes.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_identity.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_trust_chain.py, testsuite/utils.py
New test cases:
Certificate building data for the CFSSL is moved to the separate builder function.
Added possibility to create self-signed certificates.
=> Add advanced mtls tests

testsuite/tests/kuadrant/authorino/identity/api_key/conftest.py, testsuite/tests/kuadrant/authorino/metadata/test_uma.py
https://github.com/Kuadrant/kuadrant-operator/issues/127 Is fixed, so we can enable those tests again
=> Add secrets tests back to Kuadrant

testsuite/tests/kuadrant/reconciliation/test_httproute_delete.py
Closes https://github.com/Kuadrant/kuadrant-operator/issues/124
Depends on #175
=> Add tests for HTTPRoute delete reconciliation

testsuite/openshift/objects/rate_limit.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/conftest.py, testsuite/tests/kuadrant/limitador/conftest.py, testsuite/tests/kuadrant/limitador/test_basic_limit.py, testsuite/tests/kuadrant/limitador/test_multiple_iterations.py, testsuite/utils.py
- Simple limit test
- Multiple iteration test
Closes #166, #165
=> Add basic Limitador tests

config/settings.local.yaml.tpl, pyproject.toml, testsuite/config/__init__.py, testsuite/objects/__init__.py, testsuite/oidc/rhsso/__init__.py, testsuite/openshift/client.py, testsuite/openshift/envoy.py, testsuite/openshift/objects/authorino.py, testsuite/resources/wristband/envoy.yaml, testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/tests/kuadrant/authorino/wristband/conftest.py, testsuite/tests/kuadrant/authorino/wristband/test_wristband.py
- Move cfssl client to the root conftest
- Add Edge (Wristband) envoy template
- Add Edge Authentication tests
- Test for the successful authorization with issued wristband token (200 OK)
- Test for the failed authorization with an incorrect token (401 Unauthorized)
- Test for the claims verification in the decoded wristband token
Closes #15
=> Add Edge Authentication tests

testsuite/hyperfoil/__init__.py
- It validates but does not run!! the benchmark
- This was the cause for our problem with Hyperfoil 0.25-SNAPSHOT
=> Remove validate option from Hyperfoil

testsuite/objects/sections.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/caching/metadata/conftest.py, testsuite/tests/kuadrant/authorino/caching/metadata/test_caching.py, testsuite/tests/kuadrant/authorino/caching/metadata/test_not_cached.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_response_condition.py, testsuite/tests/kuadrant/authorino/identity/anonymous/test_anonymous_context.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_api_key_context.py, testsuite/tests/kuadrant/authorino/metadata/test_multi_element_json.py, testsuite/tests/kuadrant/authorino/priority/conftest.py, testsuite/tests/kuadrant/authorino/priority/test_dependency.py, testsuite/tests/kuadrant/authorino/priority/test_sequence_anonymous.py, testsuite/tests/kuadrant/authorino/priority/test_sequence_api_key.py, testsuite/utils.py
- Add simple debugging response - `response.add_simple`
- Used when you need to return some authjson section and do not care about details 
- Refactor extract_from_response
- Uses weakget
- same default values as `response.add_simple`
=> Add simple response

testsuite/objects/__init__.py, testsuite/objects/sections.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/caching/metadata/test_caching.py, testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py
This PR includes:
- Refactor of Value class to three dataclasses removing redundant test of exclusivity.
- Replacing usage of `dataclasses.asdict()` and direct `object.to_dict()` method calls in favor of new `to_dict()` function
=> Dataclasses refactor and add new to_dict function

testsuite/openshift/envoy.py, testsuite/openshift/httpbin.py, testsuite/tests/kuadrant/authorino/dinosaur/conftest.py
`importlib.resources.path` deprecated since Python 3.11 in favor of `importlib.resources.files`
=> Replaces deprecated files() API

config/settings.local.yaml.tpl, testsuite/objects/__init__.py, testsuite/openshift/client.py, testsuite/openshift/objects/authorino.py, testsuite/openshift/objects/metrics/__init__.py, testsuite/openshift/objects/metrics/prometheus.py, testsuite/openshift/objects/metrics/service_monitor.py, testsuite/openshift/types/__init__.py, testsuite/openshift/types/routes.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py, testsuite/tests/kuadrant/authorino/metrics/test_deep_metrics.py, testsuite/tests/kuadrant/authorino/metrics/test_metrics.py
Fix routes iteration method (**\_\_iter\_\_**).
Add real Openshift token acquiring possibility.
Add Authorino metrics endpoint getter (Preexisting and new Authorino).
Add Prometheus and Metrics clients for easier metrics fetching.
Add Authorino metrics and server-metrics tests.
Test cases:
Closes #106
=> Add tests for Common feature - Metrics

testsuite/objects/__init__.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_extended_properties.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_overwriting.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_token_normalization.py
Contains also:
-  bugfix of "Add plain identity" function https://github.com/Kuadrant/testsuite/pull/212#discussion_r1272674382
- Replace Union with more native type marking https://github.com/Kuadrant/testsuite/pull/212#discussion_r1281998698
- ~Replace custom `asdict()` in `ValueFrom` with dict transformation https://github.com/Kuadrant/testsuite/pull/212#discussion_r1282710508~ 
- Fix typo in docstring for `asdict()` https://github.com/Kuadrant/testsuite/pull/212#discussion_r1285922191
- Change `add_item` function to force keyword-only common_features arguments https://github.com/Kuadrant/testsuite/pull/212#discussion_r1305881457
Closes #108
=> Add tests for extended_properties feature

testsuite/openshift/objects/gateway_api/gateway.py, testsuite/tests/conftest.py, testsuite/tests/mgc/test_basic.py
Depends on #231. Unifies both `Gateway` and `MGCGateway` into one workflow, where the gateway object is interchangeable and introduces `GatewayProxy` wrapper, which serves as a Proxy implementation.
=> Unify gateways

testsuite/openshift/client.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py, testsuite/tests/kuadrant/authorino/metrics/test_deep_metrics.py
=> Fix metrics tests broken by reformat

testsuite/openshift/objects/gateway_api/gateway.py
- Has a different service name for a Gateway
- Breaks support for older Istio versions
=> Change testsuite to support Istio 1.19

testsuite/objects/__init__.py, testsuite/openshift/objects/auth_config/__init__.py, testsuite/openshift/objects/auth_config/auth_policy.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_response_condition.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_auth_credentials.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_extended_properties.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_overwriting.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_token_normalization.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_auth_credentials.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_rhsso_context.py, testsuite/tests/kuadrant/authorino/metrics/test_deep_metrics.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/test_wildcard_collision.py, testsuite/tests/kuadrant/authorino/operator/http/conftest.py, testsuite/tests/kuadrant/authorino/operator/sharding/conftest.py, testsuite/tests/kuadrant/authorino/priority/test_sequence_api_key.py, testsuite/tests/kuadrant/authorino/response/test_auth_json.py, testsuite/tests/kuadrant/authorino/response/test_base64.py, testsuite/tests/kuadrant/authorino/response/test_headers.py, testsuite/tests/kuadrant/authorino/response/test_multiple_responses.py, testsuite/tests/kuadrant/authorino/response/test_simple_response.py, testsuite/tests/kuadrant/authorino/test_redirect.py, testsuite/tests/kuadrant/authorino/wristband/test_wristband.py
This PR makes this testsuite compatible with newest AuthConfig/AuthPolicy v1beta2
Few notes:
- Envoy Dynamic Metadata function needs to be added in Responses section when tests for it will be created
- **Wristband tests are for now skipped!** 
- Test for Custom deny code/body/headers need to be created
- testsuite/tests/kuadrant/authorino/response/test_headers.py is maybe not needed as wrapperKey no longer exists or needs some rewrite
=> Authpolicy v1beta2 reformat

.github/workflows/build_release_image.yml, .github/workflows/build_unstable_image.yml, .github/workflows/promote_to_latest.yml
Currently, the image is only built with each release, which requires manual steps to do. This PR proposes automatic builds to the `unstable` tag with occasional promotes to `latest` without doing a full release to create more frequent builds.
In the future we need to revise how we do releases and this should suffice until we figure it out.
=> Add automatic builds

testsuite/tests/kuadrant/authorino/identity/rhsso/test_auth_credentials.py
- Run it also on Kuadrant
- Fix wrong asserts
=> Fix test_auth_credentials.py

testsuite/tests/kuadrant/authorino/identity/rhsso/test_auth_credentials.py
Fix wrong credentials parameters that were missed in #248 
It is interesting that it was not caught in automated commit test via `mypy` tool because the variables are behind `pytest` parametrize feature.
=> Fix wrong credentials param test_auth_credentials.py

testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/wristband/conftest.py, testsuite/tests/kuadrant/authorino/wristband/test_wristband.py
- Add Dynamic envoy metadata functionality to complete refactor that was started in #248 
- Unskip wristband tests
=> Authpolicy upgrade to v2 Dynamic Envoy Metadata

testsuite/tests/kuadrant/authorino/response/test_deny_with.py
Requires #248 
Testing new `set_deny_with()` function with newly added extensions in AuthPolicy v2
=> Custom deny responses test

testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_response_condition.py
Fix bug introduced in #214 testing wrong header name resulting in always True assert. Asserted string should be `Simple` because HTTP headers capitalize first letter of header name.
=> Fix capitalizazion in test_response_condition.py test

testsuite/tests/kuadrant/authorino/metadata/test_user_info.py, testsuite/tests/kuadrant/test_rate_limit_authz.py
Realm is session-scoped and users cannot share the same email
=> Blame email for RHSSO users

.dockerignore, Dockerfile, pyproject.toml
With poetry 1.7.0 (https://python-poetry.org/blog/announcing-poetry-1.7.0/) the `setuptools` are removed when doing `install --sync`, sadly, `python-keycloak` depends on `setuptools` but has no direct dependency yet.
See https://github.com/marcospereirampj/python-keycloak/pull/505 for more details
=> Fix missing setuptools

testsuite/objects/__init__.py, testsuite/openshift/objects/__init__.py, testsuite/openshift/objects/ingress.py
`OpenShiftObject` already implements `commit` and `delete`. This PR formaly adding already existing inheritence.
=> Extend OpenShiftObject class with LifecycleObject

testsuite/openshift/objects/dnspolicy.py, testsuite/openshift/objects/gateway_api/gateway.py, testsuite/tests/mgc/conftest.py, testsuite/tests/mgc/dnspolicy/conftest.py, testsuite/tests/mgc/dnspolicy/health_check/conftest.py, testsuite/tests/mgc/dnspolicy/health_check/test_healthy_endpoint.py, testsuite/tests/mgc/dnspolicy/health_check/test_unhealthy_endpoint.py
Add basic tests for healthy-unhealthy endpoints
- Make tls plugable in MGC gateway
- Add DNSHealthCheckProbe object (automatically created by DNSPolicy)
- Add tests
Closes #254
=> Add basic tests for DNSPolicy health checks

testsuite/objects/__init__.py, testsuite/openshift/objects/auth_config/sections.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_response_condition.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_rhsso_context.py, testsuite/tests/kuadrant/authorino/metrics/test_deep_metrics.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/test_wildcard_collision.py, testsuite/tests/kuadrant/authorino/operator/http/conftest.py, testsuite/tests/kuadrant/authorino/operator/sharding/conftest.py, testsuite/tests/kuadrant/authorino/response/test_auth_json.py, testsuite/tests/kuadrant/authorino/response/test_base64.py, testsuite/tests/kuadrant/authorino/response/test_deny_with.py, testsuite/tests/kuadrant/authorino/response/test_headers.py, testsuite/tests/kuadrant/authorino/response/test_multiple_responses.py, testsuite/tests/kuadrant/authorino/response/test_simple_response.py, testsuite/tests/kuadrant/authorino/test_redirect.py, testsuite/tests/kuadrant/authorino/wristband/conftest.py, testsuite/tests/kuadrant/test_rate_limit_authz.py
As discussed with @pehala this PR refactores Responses section and usage to closer mimic real AuthConfig/AuthPolicy structure. There are 4(+1) functions in authorization object now:
- `authorization.responses.add_success_header()` - Add response as header
- `authorization.responses.add_success_dynamic()` - Add response as dynamic Envoy metadata
These functions use dataclasses contain different types of responses `JsonResponse, PlainResponse, WristbandResponse`
- `set_unauthenticated()`
- `set_unauthorized()`
These functions use dataclass `DenyResponse`
The usage of `authorization.responses.add_simple` was not changed.
=> Responses section refactor

README.md, config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config/__init__.py, testsuite/config/openshift_loader.py, testsuite/openshift/client.py, testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/identity/api_key/test_api_key_context.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py, testsuite/tests/kuadrant/authorino/wristband/conftest.py, testsuite/tests/mgc/conftest.py, testsuite/tests/mgc/dnspolicy/conftest.py, testsuite/tests/mgc/dnspolicy/health_check/conftest.py
* Rename `kuadrant` to `service_protection`
* Move `authorino` and `envoy` under `service_protection`
* Rename `mgc` to `control_plane`
* Move `kuadrant.enable` to `gateway_api`
* Change how OpenShift are configured:
* Introduce `cluster` configuration, which represent the cluster info where everything should run
* By default is completely empty, which means that whatever server user is logged in will be used
* This would be overridden if ran with MGC as the workload will be automatically moved to a spoke
* All settings in `service_protection` section are only a projects on the cluster, no other configuration is allowed
* `control_plane.spokes` and `control_plane.hub` (new settings) require a full cluster configuration, same as `cluster`
* Change `openshift()` and `openshift2()` fixtures …
=> Refactor settings structure

testsuite/httpx/__init__.py, testsuite/openshift/objects/gateway_api/route.py, testsuite/openshift/objects/route.py, testsuite/tests/kuadrant/authorino/operator/http/conftest.py, testsuite/tests/mgc/test_basic.py
* Add two new asserts to MGC tests, which ensure that in case of incorrect configuration or a bug, tests will Fail instead throwing and Exception
* Rename our HttpX client to `KuadrantClient`
=> Add has_dns_error() and has_tls_error() assert to mgc tests

testsuite/tests/kuadrant/authorino/identity/api_key/test_auth_credentials.py
Tests compared `Credentials` dataclass with a string before, which always resulted in a false condition.
=> Fix tests with credentials

testsuite/openshift/objects/gateway_api/gateway.py
`selector.union` doesn't assign to a variable by itself
=> Fix kuadrant route cleanup

testsuite/tests/kuadrant/authorino/identity/api_key/test_auth_credentials.py, testsuite/tests/kuadrant/authorino/identity/rhsso/test_auth_credentials.py, testsuite/tests/kuadrant/conftest.py, testsuite/tests/kuadrant/reconciliation/conftest.py, testsuite/tests/kuadrant/test_rate_limit_authz.py
* Identities are already cleared out on the `identity` package level, so additional clear-out is not needed
* Oidc identity is already applied by default on the `authorino` package level to the AuthConfig/AuthPolicy. Other kuadrant packages don't take advantage of the rhsso identity features
=> Remove unnecessary identities management

testsuite/policy/authorization/__init__.py, testsuite/policy/authorization/auth_config.py, testsuite/policy/authorization/sections.py, testsuite/policy/rate_limit_policy.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_authorization_condition.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_identity_condition.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_metadata_condition.py, testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_response_condition.py, testsuite/tests/kuadrant/authorino/conditions/test_patternref_expressions.py, testsuite/tests/kuadrant/authorino/conditions/test_top_level_condition.py, testsuite/tests/kuadrant/authorino/identity/extended_properties/test_token_normalization.py, testsuite/tests/kuadrant/authorino/metadata/test_user_info.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_attributes.py, testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py, testsuite/tests/kuadrant/authorino/response/test_deny_with.py
This PR:
- Renames `Rule` to `Pattern` to better reflect the real use.
- Adds new dataclasses `AnyPatterns` and `AllPatterns` which serve as logical operators OR and AND for Patterns.
- Adds new function to AuthConfig/Policy `add_patterns()` which adds **named patterns** that can be referenced with `PatternRef`.
- Add new test testing the logical operators functionality.
This PR is prerequisite before starting to work on issue #234
=> Add logical operations on Patterns and Named patterns + new test

testsuite/policy/authorization/auth_config.py, testsuite/policy/rate_limit_policy.py, testsuite/tests/kuadrant/authorino/caching/metadata/conftest.py, testsuite/tests/kuadrant/authorino/conftest.py, testsuite/tests/kuadrant/authorino/metadata/test_uma.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py, testsuite/tests/kuadrant/authorino/wristband/conftest.py, testsuite/tests/kuadrant/conftest.py, testsuite/tests/kuadrant/limitador/conftest.py, testsuite/tests/kuadrant/reconciliation/conftest.py
- Add wait-for-ready methods for authorization and `RateLimitPolicy` components
- Add wait-for-ready method calls after the kuadrants components commit
- Add uma test dependency for client secret so it is created before authorization using it
=> Add kuadrant components wait-for-ready

testsuite/policy/authorization/auth_config.py, testsuite/policy/authorization/auth_policy.py, testsuite/tests/kuadrant/gateway/conftest.py, testsuite/tests/kuadrant/gateway/test_basic.py
AuthPolicy attached straight to gateway
- Change authorization `targetRef` parameter name from `route` to `target`
- Add smoke test for AuthPolicy attached straight to gateway
Also an automatization for the following issue: https://github.com/Kuadrant/kuadrant-operator/pull/287
closes #269
=> Add test for gateway attached to AuthPolicy

testsuite/gateway/__init__.py, testsuite/gateway/gateway_api/route.py, testsuite/policy/rate_limit_policy.py, testsuite/tests/kuadrant/reconciliation/test_httproute_matches.py, testsuite/utils.py
This PR creates two new sets of objects:
- `RouteSelect`: https://docs.kuadrant.io/kuadrant-operator/doc/reference/route-selectors/#routeselector
- `HTTP Route Matchers`: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteMatch
The placement of these resources can be discussed as I was not 100% sure.
Tests will be added later to this PR.
Usage example:
```
selector = RouteSelector(
RouteMatch(
path=HTTPPathMatch(type=MatchType.EXACT, value="/get"),
headers=[HeadersMatch(name="header", value="value"), HeadersMatch(name="another", value="value")],
query_params=[HTTPQueryParamsMatch(name="param", value="value")]
method=HTTPMethod.GET,
)
)
rate_limit.add_limit("multiple", [limit], route_selectors=[selector])
```
=> Add Route Select for Rate Limit

testsuite/tests/kuadrant/conftest.py, testsuite/tests/kuadrant/limitador/test_basic_limit.py, testsuite/tests/kuadrant/limitador/test_multiple_iterations.py, testsuite/tests/kuadrant/limitador/test_route_rule.py, testsuite/tests/kuadrant/test_rate_limit_authz.py
In addition, this PR propose a solution to RLP creation for Route and Gateway
=> Add RLP route rule test

testsuite/gateway/__init__.py
Fix the bug where testsuite can't initialize the `EnvoyVirtualRoute` class because of unimplemented abstract methods. Introduced in https://github.com/Kuadrant/testsuite/pull/316
=> Remove unimplemented abstract method from envoy route

config/settings.local.yaml.tpl, testsuite/utils.py
Resolve the issue where if testsuite is executed from docker then it will use the uid of the user for objects name instead of the user name itself (e.g. `testsuite:1001`). Resolved by changing to the appropriate whoami standard function: `getpass.getuser()`
From https://docs.python.org/3/library/getpass.html:
_Return the “login name” of the user._
_This function checks the environment variables LOGNAME, USER, LNAME and USERNAME, in order, and returns the value of the first one which is set to a non-empty string. If none are set, the login name from the password database is returned on systems which support the [pwd](https://docs.python.org/3/library/pwd.html#module-pwd) module, otherwise, an exception is raised._
_In general, this function should be preferred over …
=> Change whoami with os.getlogin to getpass.getuser

testsuite/config/__init__.py
DefaultValueValidator validator only triggers when the value is missing entirely, however after first validation it became None instead and subsequent validation would pass.
=> Fix DefaultValueValidator validating only once

Makefile, config/settings.local.yaml.tpl, config/settings.yaml, testsuite/capabilities.py, testsuite/config/__init__.py, testsuite/tests/conftest.py
Makes configuring standalone run to be all done through flags instead of config + flag
=> Replace standalone config option for --standalone flag

testsuite/openshift/__init__.py, testsuite/tests/mgc/reconciliation/__init__.py, testsuite/tests/mgc/reconciliation/test_gw_doesnt_exist.py, testsuite/tests/mgc/reconciliation/test_invalid_issuer_reference.py, testsuite/tests/mgc/reconciliation/test_same_target.py
* Tests for basic reconciliation scenarios for interactions between DNSPolicy and Gateway
* Introduce `wait_until` function for `OpenShiftObject`
=> Add reconciliation tests for DNSPolicy/TLSPolicy

testsuite/httpx/auth.py, testsuite/openshift/service_account.py, testsuite/policy/authorization/sections.py, testsuite/tests/kuadrant/authorino/identity/token_review/conftest.py, testsuite/tests/kuadrant/authorino/identity/token_review/test_audiences.py, testsuite/tests/kuadrant/authorino/identity/token_review/test_host.py
Authorino kubernetes token-review identity tests
- Add service account get-bound-token function to the OpenshiftClient
- Add conftest with service account creating fixture
- Add test for token-review default audience (requested hostname)
- Add test for token-review custom audiences
closes #110
=> Add kubernetes token-review identity tests

pyproject.toml
As it is not needed and it has currently bug causing pytest crash https://github.com/box/flaky/issues/198
=> Remove flaky library

testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py, testsuite/tests/kuadrant/authorino/operator/clusterwide/test_wildcard_collision.py
First authconfig now contains only first hostname, second authconfig - only second hostname.
The wildcard collision test is divided into 2 separate tests
=> Fix authorino clusterwide tests

testsuite/tests/kuadrant/limitador/route/conftest.py, testsuite/tests/kuadrant/limitador/route/test_limit_targeting_two_rules.py, testsuite/tests/kuadrant/limitador/route/test_multiple_same_rule.py, testsuite/tests/kuadrant/limitador/route/test_route_rule.py
This PR implements two use cases for RLP:
1. Tests that when one limit is targeting two rules, the same limit applies for them both at once.
2. Tests that when two limits are targeting one rule, one limit ends up shadowing others.
Test cases are points 5 and 6 from [RFC](https://docs.kuadrant.io/architecture/rfcs/0001-rlp-v2/#example-6-multiple-limit-definitions-targeting-the-same-httprouterule). Please think of this cases, if they are meaningful or extendable.
=> Add RLP targetting tests

testsuite/mockserver.py, testsuite/openshift/backend.py, testsuite/openshift/deployment.py, testsuite/openshift/httpbin.py, testsuite/policy/dns_policy.py, testsuite/tests/mgc/dnspolicy/health_check/test_additional_headers.py
DNSPolicy health check additional headers
- Add MockserverBackend object
- Add request expectation to the mockserver
- Add test for DNSPolicy health check additional headers
closes #252
=> Test DNSPolicy health check additional headers

testsuite/httpx/__init__.py
* Add "Server disconnected without sending a response" error to a backoff
* Do not raise AttributeError
* Proved to be more confusing
=> Enhance stability

Makefile, testsuite/capabilities.py, testsuite/config/openshift_loader.py, testsuite/tests/conftest.py
* Run Kuadrant check every time in the beginning, unless there is a `--standalone` flag
* `make test` now has `--enforce` flag
* Run Kuadrant check against default cluster, if no spokes are configured
=> Always run Kuadrant check

testsuite/utils.py
Improvement of `extract_response` function. It should attempt to extract stuff from the response regardless the response status code. There are valid use cases there, for example 500 responses might contain details about error etc.
The only good reason for skipping the actual extraction is when there is nothing to do the extraction from. In case of non-empty content the function proceeds as before (no matter what the status_code is) - it converts the content to JSON (it throws an error in case of invalid JSON) and tries to extract the data from given location.
- Return None right away if the content of the response is empty
- Trivial typo fix
Eye review might suffice. If you have a cluster you can run the whole test suite (I did that though and there were no suspicious errors, just …
=> Improve extract_response to return None for empty content only

testsuite/openshift/metrics/prometheus.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py, testsuite/tests/kuadrant/authorino/metrics/test_deep_metrics.py, testsuite/tests/kuadrant/authorino/metrics/test_metrics.py
Changes:
- Fix assert on deep-metrics tests
- Increase wait for metrics scrape
- Make a fixture that checks metrics availability on the cluster to run before other fixtures
- Add explicit id's on deep-metrics tests
=> Fix metrics tests

testsuite/openshift/metrics/prometheus.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py
- It edits Authorino, which is now session -> need to descope gateway to module
- Caused by #364 and #360
=> Override Gateway for metrics tests

testsuite/tests/kuadrant/authorino/dinosaur/test_dinosaur.py
Mark dinosaur tests as expected fail due to https://github.com/Kuadrant/testsuite/issues/378
=> Mark dinosaur tests as excepted fail

Makefile, pyproject.toml
* This means that it will report a Failure when `xfail` test passes
=> Use xfail_strict

testsuite/oidc/rhsso/objects.py
Newer Keycloak versions require that name and surname are setup on a new user account for it to be verified and accessible
=> Setup default name and surname for keycloak user

README.md, config/settings.yaml, testsuite/config/__init__.py, testsuite/tests/kuadrant/gateway/conftest.py, testsuite/tests/kuadrant/gateway/test_external_ca.py
* Add configuration options for ClusterIssuer names used in tests
* One option for selfsigned and one option for letsencrypt one
* Depends on #385
=> Configurable issuer

Makefile
This make target will clean objects from Openshift cluster created by current user or additionally any other user when specified like so: 
```
USER=<name> make clean
```
Testsuite by default cleans up these objects but if test ends in error it is common some objects will not be removed.
This make target will make it easy to clean such left-overs while developing tests.
Please comment if I forgot some CR categories!
Note:
Yes the construction `$\` followed by new-line is [official](https://www.gnu.org/software/make/manual/html_node/Splitting-Lines.html) way to split string to multiple lines...
=> Add make clean target

testsuite/openshift/kuadrant.py, testsuite/tests/conftest.py, testsuite/tests/kuadrant/reconciliation/cr_configuration/test_reconcile_limitador.py
Closes https://github.com/Kuadrant/testsuite/issues/326
=> Add tests for Reconcile Sub Component Limitador CR

testsuite/config/exposer.py
Not sure if there is better way to handle this specific case, and I am not sure if this is a bug with pylint.
Introduced in pylint 3.2.0
=> Ignore useless-return

testsuite/httpx/__init__.py, testsuite/tests/kuadrant/reconciliation/conftest.py, testsuite/tests/kuadrant/reconciliation/test_httproute_delete.py, testsuite/tests/kuadrant/reconciliation/test_httproute_hosts.py, testsuite/tests/kuadrant/reconciliation/test_httproute_matches.py
* Explicitly sets retry codes on a client to have correct backoff
* Allow setting retry codes in client
Fixes #181
=> Fix flaky reconciliation tests

Makefile, testsuite/config/__init__.py, testsuite/config/exposer.py, testsuite/config/tools.py, testsuite/gateway/__init__.py, testsuite/gateway/envoy/__init__.py, testsuite/gateway/exposers.py, testsuite/gateway/gateway_api/gateway.py, testsuite/openshift/client.py, testsuite/openshift/service.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py, testsuite/tests/kuadrant/authorino/operator/raw_http/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py
* Use LoadBalancer service for tools
* https://github.com/3scale-qe/tools/pull/36
* RHSSO is still not done in that PR
* Add `not standalone_only` to test target
* Fix Prometheus check for metrics tests
* Add KindExposer
* Some tests needs to be explicitly skipped (TLS, raw_http) when used with Kind exposed
=> Add support for Kind

README.md, config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config/__init__.py, testsuite/tests/kuadrant/gateway/conftest.py, testsuite/tests/kuadrant/gateway/test_external_ca.py
The Letsecrypt issuer requires a Secret which provides secret for DNS01 verification. If ClusterIssuer object is used, the Secret needs to be stored in the namespace where the CertManager operator is installed. I propose using Issuer object inside the testing namespace which already contains secrets for DNSPolicy testing (the `mgc-aws-credentials` and `mgc-gcp-credentials`) to keep all the secrets in the same namespace. Another reason is to prevent accidental deletion of the secret in case of nightly testing.
This PR also adds entries to settings template file.
=> Refactor clusterissuer to issuer

Makefile, testsuite/tests/kuadrant/authorino/dinosaur/conftest.py, testsuite/tests/kuadrant/authorino/dinosaur/test_dinosaur.py
* You cannot add custom attributes like we did before, you need to register them first. This is temporary fix that removes one test-case until #396 is done
* Fix xfail
=> Fix failing dinosaur test on Keycloak 24

testsuite/tests/kuadrant/authorino/authorization/opa/test_authorization_services.py
This is a further improvement of https://github.com/Kuadrant/testsuite/pull/412
Instead of having several endpoints hard-coded the well known endpoints are used.
All the hard-coded endpoints replaced with endpoints from `uma_well_known`
Client ID and secret got differently so that `rego_policy` fixture is not dependent on `keycloak` fixture directly
The `rego_policy` and `authorization` fixtures moved a bit down after `owner_uma` fixture since these two now defends on `owner_uma`.
Removal of `# pylint: disable=line-too-long`
Eye review, run the test to see that it passes
=> Use uma_well_known endpoints in Rego Policy

testsuite/tests/kuadrant/gateway/reconciliation/test_gw_doesnt_exist.py
* That function doesn't exist
* Guess who broke the tests by using non-existing function that he planned on writing later
=> Fix test_gw_doesnt_exist.py

testsuite/openshift/service.py
* Since we deploy also Services with LoadBalancer type, it makes sense to increase to Gateway levels
=> Increase service delete timeout

testsuite/openshift/metrics/prometheus.py, testsuite/openshift/metrics/service_monitor.py, testsuite/tests/kuadrant/authorino/metrics/conftest.py, testsuite/tests/kuadrant/authorino/metrics/test_deep_metrics.py, testsuite/tests/kuadrant/authorino/metrics/test_metrics.py
- Separate wait for reconciliation
- Increase timeout to 350 second 
- Make Prometheus a Lifecycle object
- Move client stuff to commit  
- Add default Interval for MetricsEndpoint
- To better aim new wait_for_scrape backoff 
- Use ServiceMonitor as base for methods instead of `service_url`
- I found it more natural as that is the actual metric definition
=> Rework Prometheus

testsuite/openshift/__init__.py, testsuite/openshift/authorino.py, testsuite/openshift/kuadrant.py, testsuite/tests/kuadrant/reconciliation/cr_configuration/test_reconcile_limitador.py
This PR adds dunder `__getitem__` and `__setitem__` methods for CR objects. Also Implements authorino-like and limitador-like objects for Kuadrant CR to enable similar manipulation with Limitador and sub-component Limitador from Kuadrant CR.
I had to remove `from testsuite.config import settings` from utils because of cyclical import.
=> Add support methods for CR objects

testsuite/gateway/gateway_api/gateway.py
In case of cert-manager operator not being properly installed or the Issuer for Lets Encrypt is not configured properly an appropriate error is raised.
=> Add skip if cert-manager not configured

testsuite/tests/conftest.py, testsuite/tests/kuadrant/authorino/dinosaur/conftest.py
This seems to delete Keycloak Realms once the tests are over.
Eye review if it makes sense.
Run single test and verify there is no Keycloak Realm created by the test run there once the test is over. Try  `./kuadrant/authorino/dinosaur` test for instance as this one creates one additional (`admin`) Realm.
Run the whole test suite (`make kuadrant`) and verify that there is no Keycloak Realm created by the testsuite run present once the testsuite execution is over. For a quicker validation you can mark a few tests as "keycloak":
`pytestmark = [pytest.mark.authorino, pytest.mark.keycloak]`
Make sure that the marked tests use Keycloak and be sure to mark the `./kuadrant/authorino/dinosaur` test.
Then create a "keycloak" make target in Makefile:
```
keycloak: ## Run only keycloak related tests …
```
=> Cleanup of Keycloak Realms created for tests

testsuite/tests/conftest.py
request variable is required to add a realm clean-up finalizer to the fixture
=> Fix keycloak fixture unknown variable

testsuite/gateway/gateway_api/gateway.py, testsuite/openshift/__init__.py, testsuite/openshift/deployment.py, testsuite/openshift/ingress.py, testsuite/policy/__init__.py, testsuite/policy/authorization/auth_config.py, testsuite/policy/rate_limit_policy.py, testsuite/policy/tls_policy.py
- Timeouts now return human readable message instead of an error for timeout
- Any other errors will be propagated as usual 
- Use wait_until instead of until_all()
- Lower default timeout from 90sec to 60sec
- Everything passed on my machine, we can see if it works (or I can delete it based on review)
=> Improve wait_for_ready timeout errors

Dockerfile, testsuite/__init__.py, testsuite/openshift/client.py
* Replaces `oc` binary with `kubectl`
* This is not configurable because it needs to be resolved before configuration is parsed
* Replace whoami command with kubeconfig introspection
* Replace binary in testsuite image
=> Use kubectl instead of oc

testsuite/config/exposer.py, testsuite/gateway/exposers.py, testsuite/tests/kuadrant/authorino/operator/raw_http/conftest.py, testsuite/tests/kuadrant/authorino/operator/tls/conftest.py
Since we are using LoadBalancer services, there is no reason why the previous "Kind" exposer should not work on pure Kubernetes. I tested it with Openshift and it works as well.
=> Add Kubernetes exposer

config/settings.local.yaml.tpl, config/settings.yaml, testsuite/config/exposer.py
* Automatic exposer detection
* No longer need to explicitly state `openshift `or `kind `
* WIll use OpenShift if routes exist and Kubernetes otherwise
Depends on #448
=> Automatic exposer detection

testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py
ref: https://docs.kuadrant.io/authorino/docs/features/#kubernetes-subjectaccessreview-authorizationkubernetessubjectaccessreview
P.S. Probably also failing only now because of the change to kubectl
=> Fix wrong key name in webhook test

testsuite/policy/__init__.py, testsuite/policy/authorization/auth_policy.py, testsuite/tests/kuadrant/identical_hostnames/conftest.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_auth_on_gw_and_route.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_auth_on_routes.py
Partially addresses https://github.com/Kuadrant/testsuite/issues/406
It covers two scenarios, both testing current behavior
1) Two AuthPolicies being attached to GW and HTTPRoute with identical hostname respectively
2) Two AuthPolicies being attached to two HTTPRoutes with identical hostname each
For details see https://github.com/Kuadrant/kuadrant-operator/blob/main/doc/auth.md#limitation-multiple-network-resources-with-identical-hostnames
Eye review, execute both tests and make sure they pass.
I will proceed with RateLimitPolicy (RLP) scenarios once this is reviewed so that I can incorporate feedback from this PR there. The 1) scenario for RLP is identical, I will think of using parametrized fixture called `policy` instead of having two identical tests one using AuthPolicy and other …
=> Added identical hostnames test for AuthPolicy

testsuite/tests/kuadrant/gateway/reconciliation/test_invalid_issuer_reference.py
`gateway.reference` returns also `namespace`, which is not supported for issuers
=> Use CustomReference in test_invalid_issuer_reference.py

Makefile
Makefile syntax is pain. Closes #418 
- Fixes error of route object is not known in Kind envirnment
- Silences unnecessary line repeats (with use of `@`) and adds information on whose users objects are getting deleted
- Removes `oc` dependency in favor of `kubectl` 
- Better specification of resource objects by their true name
- Delete authorino objects first for faster deletion - I just moved it up the list
=> Fix make clean to work on Kind

testsuite/policy/__init__.py, testsuite/tests/kuadrant/identical_hostnames/conftest.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_auth_on_gw_and_route.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_auth_on_routes.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_rlp_on_gw_and_route.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_rlp_on_routes.py
Partially addresses https://github.com/Kuadrant/testsuite/issues/406
Follows up for https://github.com/Kuadrant/testsuite/pull/439 which added similar tests for AuthPolicy, this PR does the same for RateLimitPolicy (RLP).
It covers two scenarios, both testing current behavior
1. Two RLPs being attached to GW and HTTPRoute with identical hostname respectively
2. Two RLPs being attached to two HTTPRoutes with identical hostname each
For details see https://github.com/Kuadrant/kuadrant-operator/blob/main/doc/rate-limiting.md#limitation-multiple-network-resources-with-identical-hostnames
Note that the 1. scenario has been fixed in the meantime, doc is not up-to-date. The GW RLP is now partially enforced meaning that it is actually applied on the route-b. Partially enforced policy has …
=> Add identical hostnames test for RateLimitPolicy

testsuite/openshift/__init__.py, testsuite/openshift/service.py, testsuite/tests/conftest.py
Advantage: No need to specify committed when fetching object from Kubernetes
Disadvantage: One call to Kubernetes to check if it exists per object (it is cached)
Let me know what you think :)
=> Remove need to specify committed property

Makefile, config/settings.local.yaml.tpl, config/settings.yaml, testsuite/gateway/gateway_api/route.py, testsuite/kuadrantctl.py, testsuite/oas.py, testsuite/openshift/client.py, testsuite/resources/oas/base_httpbin.yaml, testsuite/tests/kuadrantctl/cli/test_basic_commands.py, testsuite/tests/kuadrantctl/cli/test_simple_auth.py, testsuite/tests/kuadrantctl/cli/test_simple_limit.py, testsuite/tests/kuadrantctl/cli/test_simple_route.py, testsuite/tests/kuadrantctl/conftest.py
* Kickoff of Kuadrantctl tests
* Due to significant rework, works with only 0.2.4-alpha and newer releases 
* New top level test folder `tests/kuadrantctl` and target `make kuadrantctl`
* Minimal abstraction, 90% things are done directly and can be reproduced easily
* OAS manipulation
* OAS is loaded as Pure OAS, that is further customized runtime by adding security or x-kuadrant fields
* ~~Customization done in two parts `base_oas` and `oas_kuadrant` fixtures~~
* ~~`base_oas` is for editing pure OAS specs, i.e adding security constrains~~
* ~~`oas_kuadrant` is for adding x-kuadrant fields~~
~~Reviewable but not mergable due to a few outstanding bugs and enhancements:~~
Gonna be merged even with temporary fixes due to outstandiong issues with `kuadrantctl` itself …
=> Add Kuadrantctl tests

testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_rlp_on_gw_and_route.py, testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_rlp_on_routes.py
No need to `retry_client` because `wait_for_ready` is sufficient. At the beginning of the test the RLP is partially enforced and `wait_for_ready` waits for it to become fully enforced
Run the test:
`$ make testsuite/tests/kuadrant/identical_hostnames/test_identical_hostnames_rlp_on_gw_and_route.py`
=> Remove retry since wait_for_ready is sufficient

testsuite/tests/singlecluster/identical_hostnames/test_identical_hostnames_auth_on_gw_and_route_desired.py, testsuite/tests/singlecluster/identical_hostnames/test_identical_hostnames_on_routes_desired.py
Last piece to address https://github.com/Kuadrant/testsuite/issues/406
Follows up on https://github.com/Kuadrant/testsuite/pull/439 and https://github.com/Kuadrant/testsuite/pull/462 which added similar tests for AuthPolicy and  RateLimitPolicy (RLP) respectively, but these tests validating current behavior.
The tests in this PR cover two scenarios, both testing desired behavior. Desired behavior means that Kuadrant does not behave like that yet so the tests are expected to fail. Once they start passing it means that implementation has changed and it would be good to take a closer look how and if that makes sense and update the testsuite accordingly.
Test that 2nd Gateway-attached AuthPolicy is actually enforced on route (currently it states that it is enforced but effectively it is …
=> Add identical hostnames tests for desired behavior

testsuite/oidc/keycloak/__init__.py
- We are using http by default, no verification needed
=> Remove verify=false from Keycloak

testsuite/kubernetes/client.py
This could cause incorrect reporting, since it would show currently active cluster info instead
=> Fix incorrect api_url/token in unconnected clusters

testsuite/oidc/keycloak/__init__.py, testsuite/tests/singlecluster/authorino/operator/tls/test_webhook.py
- Mypy no longer throws warning/note
- Included unneeded reorg of imports, not sure if it matter here
=> Remove typing annotation that were never checked

testsuite/kubernetes/metrics/prometheus.py, testsuite/mockserver.py, testsuite/tests/conftest.py, testsuite/tests/singlecluster/authorino/caching/metadata/conftest.py, testsuite/tests/singlecluster/authorino/metrics/conftest.py
* Client is required now
* Fixture will take care of client creation and cleaning up and initial setup (auth + verify)
* Remove verify=false from Mockserver, we use HTTP anyways   
* Small updates to fixtures that use that
* Tracing will get separate PR later with bigger changes
=> Unify ApyProxy clients

testsuite/prometheus.py, testsuite/tests/singlecluster/authorino/metrics/conftest.py
A few small prometheus tweaks:
- Remove namespace from prometheus queries
- Change prometheus fixture to the package scope
- Fix pytest.skip after yield (last metrics test was always skipped)
=> Remove namespace from prometheus queries

testsuite/tests/singlecluster/test_rate_limit_anonymous.py
The test was renamed because there already is a test with identical name (https://github.com/Kuadrant/testsuite/blob/main/testsuite/tests/singlecluster/authorino/identity/anonymous/test_anonymous_identity.py#L15) which causes troubles in ReportPortal
Eye review should suffice.
=> Rename anonymous rate limiting test

testsuite/gateway/gateway_api/gateway.py, testsuite/gateway/gateway_api/route.py
Due to merge of https://github.com/Kuadrant/kuadrant-operator/pull/780 we need to remove namespace from references in AuthPolicy and other CR. This should be the minimal change to achieve this.
=> Remove namespace from reference

Makefile
So we clean the Gateways.
Not sure when this changed but keeping two names for gateways should not be a problem anyways.
=> Add another gateway CR name for cleaning

testsuite/kubernetes/service.py
Openshift Service resource of LoadBalancer type might have EXTERNAL-IP in form of standartd static IP or in form of hostname
See
```
$ oc get service keycloak -n tools
NAME       TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)          AGE
keycloak   LoadBalancer   172.30.137.193   10.0.190.138   8080:31556/TCP   13d
```
versus
```
$ oc get service keycloak -n tools
NAME       TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)          AGE
keycloak   LoadBalancer   172.30.56.116   a9b2f08c4b3154094ae774fbcbb2e642-1403130510.us-west-2.elb.amazonaws.com   8080:32470/TCP   42m
```
This PR should allow the testsuite to work if EXTERNAL-IP is configured either way.
Eye review. You can run a single test that uses keycloak …
=> Using Hostname if external IP is not found

testsuite/tests/singlecluster/gateway/reconciliation/test_gateway_listeners_dns.py, testsuite/utils.py
This PR addes new test that checks for this bug: https://github.com/Kuadrant/kuadrant-operator/issues/794
Part of work on https://github.com/Kuadrant/testsuite/issues/308
=> Add Gateway listener dns test

testsuite/tests/singlecluster/overrides/test_basic_auth.py, testsuite/tests/singlecluster/overrides/test_basic_rate_limit.py, testsuite/tests/singlecluster/overrides/test_route_override.py, testsuite/tests/singlecluster/overrides/test_rules_exclusivity.py
- Add tests for Overrides
Reason for regexes in checking error messages: Kuadrant/kuadrant-operator#775 , can be fixed after
Closes #380
=> Add tests for overrides

config/settings.yaml
I is better to use my quay.io. Of course it would be ideal if we have some non-person based org there for these, but this is still slightly better
`quay.io/trepel/httpbin:jsmadis` is the same as `quay.io/jsmadis/httpbin:latest`
- you can pull and inspect if you don't believe me
Validation is required due to other change, since it updates the envoy from 1.28 do 1.31.0 (latest at the moment)
`make target`
However, I did that and the result was:
`==== 23 failed, 172 passed, 8 skipped, 25 xfailed in 1311.03s (0:21:51) ===`
The 23 failures are due to issue discussed in slack - yesterdays nightly build does not contain proper version of wasm plugin and today's does not exist due to failure
=> Using trepel quay rather than no-longer red hatters ones

pyproject.toml
We never used this library and currently its printing many warnings in test report so its good time to remove it.
For verification I would just run the testsuite and see no errors or text search for `asyncio` string in code and see no results.
=> Remove pytest-asyncio lib

testsuite/tests/singlecluster/gateway/reconciliation/test_gateway_listeners_dns.py
Issue has been fixed now: https://github.com/Kuadrant/kuadrant-operator/issues/794
So now we expect this test to pass.
To verify run:
```
make testsuite/tests/singlecluster/gateway/reconciliation/test_gateway_listeners_dns.py
```
=> Remove xfail due to gateway listeneners bug being fixed

config/settings.local.yaml.tpl, testsuite/capabilities.py, testsuite/config/__init__.py, testsuite/config/exposer.py, testsuite/config/openshift_loader.py, testsuite/kuadrant/policy/dns.py, testsuite/tests/conftest.py, testsuite/tests/multicluster/conftest.py, testsuite/tests/multicluster/load_balanced/conftest.py, testsuite/tests/multicluster/load_balanced/test_load_balanced_geo.py, testsuite/tests/multicluster/load_balanced/test_unsupported_geocode.py, testsuite/tests/multicluster/test_simple_strategy.py, testsuite/tests/singlecluster/authorino/operator/clusterwide/conftest.py, testsuite/tests/singlecluster/authorino/operator/clusterwide/test_all_namespace_api_key.py, testsuite/tests/singlecluster/authorino/operator/clusterwide/test_wildcard_collision.py, testsuite/tests/singlecluster/conftest.py, testsuite/utils.py
- Change the list of additional clusters to only 2 (not required in the near feature)
- Reformat multicluster contest to support only 2 clusters
- Add geo load balancing test
- Add unsupported geocode test
Closes #496, closes #515
=> Add geo load-balancing tests

testsuite/tests/multicluster/test_simple_strategy.py
DNS resolution in the nightly pipeline should now work the same as your local dns resolver. Therefore assert for round robin strategy should also work in nightlies
Closes #495
=> Assert IPs returned in round-robin fashion in the multicluster test

Makefile
Inpiration from sister testsuite https://github.com/3scale-qe/3scale-tests/blob/376263a7b94faced2698b920f9599c39e1d38b44/Makefile#L33
Makes the html report include CSS instead of creating extra directory to keep the css file.
=> Add flag for html generation

testsuite/kuadrant/policy/dns.py, testsuite/kubernetes/secret.py, testsuite/tests/singlecluster/gateway/dnspolicy/test_invalid_credentials.py
=> Add test for invalid credentials in dns provider

config/settings.yaml
Update default settings due to the introduced change in https://github.com/Kuadrant/testsuite/pull/516
=> Update default settings

testsuite/gateway/gateway_api/gateway.py, testsuite/kuadrant/policy/__init__.py, testsuite/kuadrant/policy/dns.py, testsuite/tests/singlecluster/gateway/test_scale_listeners.py
**Changes**
- Overwrite `wait_for_ready` for DNSPolicy with timeout increased to 5 min instead of 1 min, large amount of DNS records take some time to create
- Create 2 gateways with max listeners and see if both dns policies are enforced and some random listeners are reachable
Closes #528
=> Add gateway listeners scaling test

testsuite/capabilities.py, testsuite/tests/conftest.py
This change will add image strings of deployed Kuadrants on clusters (including second cluster if defined) in pytest report header when running testsuite with make targets. This string is taken from CatalogSource object and in case the object is not found, no string will be printed. In the future this can be expanded for Kind setup, or doing smarter job in finding the right CatalogSource.
This can make debugging easier and is mostly helpful for figuring out nightly build version as the version string in Kuadrant subscription object is "0.0.0".
=> Add Kuadrant version to pytest report

scale_test/aws-credentials.yaml, scale_test/config.yaml, scale_test/gw-auth-policy.yaml, scale_test/gw-dns-policy.yaml, scale_test/gw-rlp.yaml, scale_test/gw-tls-policy.yaml, scale_test/gw.yaml, scale_test/httpbin-deployment.yaml, scale_test/httpbin-service.yaml, scale_test/httproute-auth-policy.yaml, scale_test/httproute-rlp.yaml, scale_test/httproute.yaml, scale_test/metrics.yaml, scale_test/metrics/.gitignore, scale_test/readme.md
The config represents a scenario with:
- 1 Gateway & 1 HTTPRoute targeting the Gateway
- 1 TLSPolicy & 1 DNSPolicy targeting the Gateway
- 1 AuthPolicy & 1 RateLimitPolicy targeting the Gateway
- 1 AuthPolicy & 1 RateLimitPolicy targeting the HTTPRoute (thereby overwriting the 2 policies targeting the Gateway)
- a simple http app being exposed by the HTTPRoute
The kube-burner tool captures metrics from prometheus before and after the creation of these resources.
The resources are checked for specific status conditions before they are 'ready'.
After that, they are destroyed.
The metrics are then sent to an indexer (can be local flat files or elasticsearch/opensearch)
The readme has instructions for running the test against a local cluster with kuadrant installed, but can also be used …
=> Add initial kube-burner config and readme for perf testing

scale_test/config.yaml, scale_test/gw-auth-policy.yaml, scale_test/gw-dns-policy.yaml, scale_test/gw-rlp.yaml, scale_test/gw-tls-policy.yaml, scale_test/gw.yaml, scale_test/httproute-auth-policy.yaml, scale_test/httproute-rlp.yaml, scale_test/httproute.yaml, scale_test/readme.md
Parametrize number of GWs and Listeners in scale test via NUM_GWS and NUM_LISTENERS env vars. See readme updates for details.
Eye review might suffice. You can follow the readme if you want to be more thorough.
=> Parametrize number of GWs and Listeners in scale test

scale_test/config.yaml, scale_test/dashboard.json, scale_test/metrics.yaml
**UPDATED: 18th Oct 2024**
I've added 5 new metrics:
* aggregate cpu & memory by namespace
* aggregate cpu & memory by pod
* calculate the 99th percentile reconcile time by controller (in the kuadrant-system namespace)
There is also an initial grafana dashboard that shows these stats for each job (prep, main, cleanup).
See screenshot for how it looks.
The table/row at the top to show all jobs for the selected time range (so you can easily see and copy a uuid if it aligns to the time range you want to filter to).
The 2nd row shows all job summary info for the selected job UUID.
The 3rd row is actually a repeating row, and shows cpu & memory, and reconcile time for the selected job UUID, with 1 row per job name i.e. scale-test-preparations, scale-test-main, scale-test-cleanup
Note the …
=> Add initial dashboard and metrics

README.md, scale_test/gw-auth-policy.yaml, scale_test/httproute-auth-policy.yaml, testsuite/kuadrant/policy/authorization/auth_config.py, testsuite/kuadrant/policy/authorization/auth_policy.py
due to https://github.com/Kuadrant/kuadrant-operator/pull/924
Only major change is the removal of RouteSelectors so no other changes required.
=> AuthPolicy version bump

pyproject.toml, testsuite/tests/singlecluster/authorino/wristband/test_wristband.py
`python-jose` is no longer supported. Switch to `PyJWT` library. Also removes time-aware zone deprecation message.
=> Change unsupported jwt library

testsuite/kuadrant/policy/__init__.py, testsuite/tests/singlecluster/gateway/test_scale_listeners.py
- Make scale gateway listeners test more stable and comprehensive
- Add "affected by policy" condition to use with `.wait_until()`
=> Improve scale gateway listeners test

testsuite/kuadrant/policy/authorization/auth_policy.py
For AuthPolicy it is required to define patterns like this:
```
patterns:
apple:
allOf:
- selector: context.request.http.path
operator: eq
value: /anything/apple
```
`allOf` is required just for AuthPolicy, no for AuthConfigt
=> Update pattern-matching for AuthPolicy

testsuite/kuadrant/policy/__init__.py, testsuite/kuadrant/policy/authorization/sections.py, testsuite/kuadrant/policy/rate_limit.py, testsuite/tests/kuadrantctl/cli/test_simple_limit.py, testsuite/tests/singlecluster/defaults/test_basic_rate_limit.py, testsuite/tests/singlecluster/defaults/test_rules_exclusivity.py, testsuite/tests/singlecluster/gateway/reconciliation/test_affected_by.py, testsuite/tests/singlecluster/identical_hostnames/test_identical_hostnames_on_routes_desired.py, testsuite/tests/singlecluster/identical_hostnames/test_identical_hostnames_rlp_on_gw_and_route.py, testsuite/tests/singlecluster/identical_hostnames/test_identical_hostnames_rlp_on_routes.py, testsuite/tests/singlecluster/limitador/method/test_route_subset_method.py, testsuite/tests/singlecluster/limitador/metrics/test_metrics.py, testsuite/tests/singlecluster/limitador/route/test_limit_targeting_two_rules.py, testsuite/tests/singlecluster/limitador/route/test_multiple_same_rule.py, testsuite/tests/singlecluster/limitador/route/test_route_rule.py, testsuite/tests/singlecluster/limitador/test_basic_limit.py, testsuite/tests/singlecluster/limitador/test_multiple_iterations.py, testsuite/tests/singlecluster/overrides/test_basic_rate_limit.py, testsuite/tests/singlecluster/overrides/test_route_override.py, testsuite/tests/singlecluster/overrides/test_rules_exclusivity.py, testsuite/tests/singlecluster/test_rate_limit_anonymous.py, testsuite/tests/singlecluster/test_rate_limit_authz.py
Resolves https://github.com/Kuadrant/testsuite/issues/575
- Changes Limit object to reflect the current Limit api
- Swaps currently used Rules from RLP to CEL expressions and predicates
=> Change Limit defition to refelct v1beta3

testsuite/kuadrant/policy/authorization/auth_config.py, testsuite/kuadrant/policy/authorization/auth_policy.py, testsuite/kuadrant/policy/authorization/sections.py
In https://github.com/Kuadrant/kuadrant-operator/pull/952 some renaming was done: `spec.rules.response.success.dynamicMetadata → spec.rules.response.success.filters`. This applies only for AuthPolicy, not for AuthConfigt
=> Update AuthPolicy to use filters instead of dynamicMetadata

testsuite/kuadrant/policy/authorization/sections.py
For reason see: https://github.com/Kuadrant/testsuite/issues/579
=> Make API Key auth look for all namespaces

testsuite/gateway/gateway_api/gateway.py, testsuite/gateway/gateway_api/route.py
Fixes multiple tests in D&O along with `testsuite/tests/singlecluster/gateway/reconciliation/test_affected_by.py`
=> Added brackets around the policy name

testsuite/kuadrant/policy/authorization/auth_policy.py, testsuite/tests/singlecluster/authorino/conditions/test_top_level_condition.py, testsuite/tests/singlecluster/authorino/dinosaur/conftest.py
Fixes `test_top_level_condition.py` and dinosaur test
=> Fix top-level when conditions

testsuite/kuadrant/policy/dns.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/conftest.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_healthy_endpoint.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_healthy_endpoint_http.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_remove_endpoint.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_unhealthy_endpoint.py
Test cases:
- Healthy endpoint with TLS
- Healthy endpoint without TLS
- Unhealthy endpoint
- Endpoint removal and return
Also added classes for the health check section of the DNSPolicy and for the DNSHealthCheckProbe CR
Part of the #572
=> Add DNSPolicy health check tests

testsuite/tests/singlecluster/limitador/metrics/test_metrics.py
the name of RLP is no longer used in metrics. Now we use `targetRef` name.
=> Change prometheus query when getting metrics for limits

scale_test/config.yaml, scale_test/gw-auth-policy.yaml, scale_test/gw-dns-policy.yaml, scale_test/gw-rlp.yaml, scale_test/gw-tls-policy.yaml, scale_test/gw.yaml, scale_test/httproute-auth-policy.yaml, scale_test/httproute-rlp.yaml, scale_test/httproute.yaml, scale_test/person-secret.yaml, scale_test/readme.md
- SKIP_CLEANUP env var to skip cleanup and update readme accordingly
- Using APIKEY Auth in HTTPRoute AuthPolicies
- Necessary policy template updates required to support v1 - there were breaking changes there since v0.11
- Small change to hostname as a prep for potential addition of DNS health check - it does not support wildcards (asterisk)
Follow the readme, skip cleanup and try the curl commands as described. Then delete DNSPolcies and delete the remaining stuff via kube-burner destroy command.
Note: this only works with nightly build (November 15 and later), does not work with v1 rc4 due to https://github.com/Kuadrant/kuadrant-operator/issues/990
=> Added apikey Auth and v1 updates to scale test policies

testsuite/backend/__init__.py, testsuite/backend/httpbin.py, testsuite/backend/mockserver.py, testsuite/kubernetes/service.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_additional_headers.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_healthy_endpoint.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_remove_endpoint.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_unhealthy_endpoint.py
- Revive Mockserver backend class for additional headers test
- Add DNSPolicy health checks additional headers test
- Add tlspolicy mark to health check tests that use it
Closes #572
=> Add DNS health check additional headers test

scale_test/config.yaml, scale_test/httproute.yaml
Use sectionName in scale test so that there are not "invalid path" log entries in kuadrant operator log. Also slightly increased pause to wait after everything was done. And added pause to allow for DNSRecords to get properly removed.
Run the scale test as described in readme. You can skip the cleanup to inspect manually that it works.
=> Use sectionName in scale test

testsuite/tests/conftest.py
When using --setup-plan to print out a "tesplan", `pytest_runtest_setup` uses `has_kuadrant()` check will fail when kuadrant is not deployed, or oc has no access to any openshift. Which is not necessary when just listing tests.
Adding the condition when --setup-plan is used to skip any checks.
fixes Kuadrant/testsuite#618
=> FIX: ignoring has_kuadrant() check when --setup-plan option is used

testsuite/kuadrant/policy/authorization/sections.py, testsuite/kubernetes/cluster_role.py, testsuite/tests/singlecluster/authorino/identity/conftest.py, testsuite/tests/singlecluster/authorino/identity/subject_access_review/conftest.py, testsuite/tests/singlecluster/authorino/identity/subject_access_review/test_subject_access_review.py, testsuite/tests/singlecluster/authorino/identity/token_review/conftest.py
based on [User guide: Kubernetes RBAC for service authorization](https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/kubernetes-subjectaccessreview.md)
Added the interface for ClusterRole and ClusterRoleBinding.
For the test I added TokenReview authentication and SubjectAccessReview based on the username.
The test setup creates 2 service accounts, with one bound to the ClusterRole permitting it to access the `/get` endpoint.
=> Add test for the subject access review non resource attributes

testsuite/capabilities.py
LOW PRIORITY
In the helm deployment of Kuadrant, the secret containing login credentials to Keycloack is located under different name and key.
To verify run some keycloack test on cluster witch has Kuadrant deployed with Helm:
```
make testsuite/tests/singlecluster/authorino/identity/auth/
```
Additionally the location of CatalogSource containing information about Kuadrant version has been moved https://github.com/Kuadrant/testsuite/pull/558/commits/6ea72cb85a05cf1d6bc3be78b3f343ddfb3f3392 reflects that now.
=> Change the location of CatalogSource with Kuadrant

testsuite/kuadrant/policy/tls.py
Azure TLS ACME challenges take 7+ minutes on the multiclusters
=> Increase TLSPolicy timeout for Azure TLS ACME challenges

testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_authpolicy_target_ref.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_ratelimitpolicy_target_ref.py
Test for changing parentRef field in policies (AuthPolicy and RateLimitPolicy)
=> Test for changing parentRef field in policies (AuthPolicy and RateLimitPolicy)

.gitignore
This PR updates the .gitignore file to exclude .DS_Store files, which are macOS-specific metadata files that are not needed in the repository.
=> Update .gitignore to ignore .DS_Store files

testsuite/kuadrant/policy/authorization/sections.py, testsuite/tests/singlecluster/authorino/metadata/test_token_introspect.py
**Summary**
This PR adds token introspect test case referenced in #88.
=> Add test for token introspection.

testsuite/kuadrant/policy/authorization/auth_policy.py, testsuite/kuadrant/policy/rate_limit.py, testsuite/tests/singlecluster/defaults/test_section_targeting.py, testsuite/tests/singlecluster/overrides/test_multiple_rate_limit.py, testsuite/tests/singlecluster/overrides/test_section_targeting.py
Refined part from the https://github.com/Kuadrant/testsuite/pull/608
- Section targeting tests for gateway and route
- Multiple ratelimitpolicies test for overrides
=> D&O section target tests

testsuite/kuadrant/policy/__init__.py, testsuite/kuadrant/policy/authorization/auth_policy.py, testsuite/kuadrant/policy/rate_limit.py, testsuite/tests/singlecluster/defaults/merge/conftest.py, testsuite/tests/singlecluster/defaults/merge/same_target/conftest.py, testsuite/tests/singlecluster/defaults/merge/same_target/test_ab_strategy.py, testsuite/tests/singlecluster/defaults/merge/same_target/test_ba_startegy.py, testsuite/tests/singlecluster/defaults/merge/test_gateway_default_merge.py, testsuite/tests/singlecluster/overrides/merge/conftest.py, testsuite/tests/singlecluster/overrides/merge/same_target/conftest.py, testsuite/tests/singlecluster/overrides/merge/same_target/test_ab_strategy.py, testsuite/tests/singlecluster/overrides/merge/same_target/test_ba_startegy.py, testsuite/tests/singlecluster/overrides/merge/test_gateway_override_merge.py
Refined part of https://github.com/Kuadrant/testsuite/pull/608 with merge strategy tests only
Closes #566
=> Add tests for D&O merge strategy

testsuite/kuadrant/policy/dns.py
Some healthcheck tests failing inside pods, I'm not sure why they are failing yet. Trying to add a backoff for each failing action to see if resource creation timing is the problem
=> Add backoff to the health-check tests

testsuite/kubernetes/__init__.py
**Summary**
This PR adds assertions to the `.apply()` and `.modify_and_apply()` methods to ensure errors are raised when resource updates fail, preventing silent failures.
**Description of changes**
Following solution (b) from issue #631, the `.apply()` and `.modify_and_apply()` methods have been overridden in `KubernetesObject` to raise an assertion error when:
- A change was expected but not applied (i.e. no modification occurred)
- The apply command itself failed (returned a non-zero exit code)
**Related Issue**
Closes [#631](https://github.com/Kuadrant/testsuite/issues/631)
=> Add assertions to apply() and modify_and_apply() methods

testsuite/tests/singlecluster/authorino/dinosaur/conftest.py
Missing re-reaise will cause test fails in case AuthConfig/Policy was not created instead of error in creation.
Eye review is enough in my opinion.
=> Add re-raise for dinosaur tests

testsuite/tests/singlecluster/gateway/reconciliation/listeners/test_gateway_listeners_dns.py
Gateway cant have 0 listeners. This change wont change the test case as this is what I wanted to test in the first place. ie. Changing the hostname of the single listener.
Run the test
```sh
make testsuite/tests/singlecluster/gateway/reconciliation/listeners/test_gateway_listeners_dns.py
```
=> Change the listener hostname directly - fix test_change_listener test

testsuite/gateway/gateway_api/gateway.py, testsuite/httpx/__init__.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_authpolicy_target_ref.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_dnspolicy_target_ref.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_ratelimitpolicy_target_ref.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_tlspolicy_target_ref.py
**Summary**
This PR adds reconciliation tests focusing on targetRef updates across different policies. 
**Test Cases Covered**
* DNSPolicy: Verifies DNS records are updated accordingly when changing `targetRef` from Gateway 1 (hostname 1) to Gateway 2 (hostname 2).
* TLSPolicy: Verifies TLS records are updated accordingly when changing `targetRef` from Gateway 1 (hostname 1) to Gateway 2 (hostname 2).
* AuthPolicy and RateLimitPolicy were covered in PR #622), but were slightly modified in this PR.
**Related Issue**
Closes [#307](https://github.com/Kuadrant/testsuite/issues/307)
=> Add tests for changing targetRef field in policies

testsuite/httpx/__init__.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_authpolicy_target_ref.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_tlspolicy_target_ref.py
This PR updates the failing `change_targetref` tests as described in issue #664.
**Changes:**
- Solution for now is to add `time.sleep(10)` to both tests, comments in code explain reasoning. In the future, when issue #660 is addressed, there could be a better solution in place of this.
- Added `has_tls_error() `method to `testsuite/httpx/__init__.py`
- Updated assertions in `testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_tlspolicy_target_ref.py` to use `assert response.has_tls_error()` instead of directly checking for a specific SSL error message via `response.has_error("[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol")`.
=> Update failing change_targetref tests

testsuite/tests/singlecluster/reconciliation/test_httproute_delete.py
Update old httproute-delete test to see why exactly it's failing in nightly runs
```sh
make testsuite/tests/singlecluster/reconciliation/test_httproute_delete.py
```
=> Update httproute-delete test

Makefile
Run multicluster tests with -n2 instead of sequentially in Makefile
`make multicluster`
=> Run multicluster tests with -n2

testsuite/kuadrant/policy/dns.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/conftest.py, testsuite/tests/singlecluster/gateway/dnspolicy/health_check/test_remove_endpoint.py
`.is_healthy()` was failing inside the test so I fix it
`make testsuite/tests/singlecluster/gateway/dnspolicy/health_check/`
=> Improve wait on health-check tests

testsuite/tests/singlecluster/authorino/collisions/auth_policy/test_collisions.py, testsuite/tests/singlecluster/authorino/collisions/rate_limit/test_collisions.py, testsuite/tests/singlecluster/authorino/collisions/test_collisions.py, testsuite/tests/singlecluster/limitador/collisions/test_collisions.py
This PR aims to fix issue: #571 
Added collision test for both auth policies and rate limits when attached to the same target.
=> Collision tests for policies.

testsuite/tests/singlecluster/authorino/collisions/test_collisions.py
Added marker on authorization policy collisions tests for kuadrant only as it is not supported in standalone mode.
=> Added marker on collision tests for kuadrant only.

testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_ratelimitpolicy_target_ref.py
**Description**
This PR aims to fix test `testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_ratelimitpolicy_target_ref.py` which has been failing intermittently on the nightly runs.
**Changes**
- Added wait_until(...) assertions to ensure Gateway resources reflect the expected RateLimitPolicy state before proceeding
=> Update ratelimitpolicy change_targetref test

testsuite/tests/multicluster/test_simple_strategy.py
To test "Simple strategy" we do not really need to check the round-robin way of returned DNS responses. In the description of [AWS route 53 Simple strategy](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-simple.html) it is stated that they return the responses at random. The standard DNS behavior when multiple A records exist for single name is to return the order in round-robin or random fashion. In ideal world how this test is currently written we would want to expect this behavior. But due to caching, recursive resolver different implementation, system dns implementation or the randomness we cant always guarantee this behavior to be exact.
Checking that in the response are all A records that are expected and not bothering with their orders seems to me as …
=> Change simple dns strategy test case in more DNS way

testsuite/gateway/gateway_api/gateway.py
Instead of using hard-coded 'istio' the proper name of GatewayClass CR is used based on what is actually present in cluster.
Reason: in OCP v4.19 the GatewayClass CR won't be called 'istio' but 'openshift-default' by default. Also we might need to support other names - users can create GatewayClasse CR with arbitrary name and Kuadrant supports that so our test suite should be ready for that too.
I don't think that we have OCP v4.19 cluster with 'openshift-default' GatewayClass CR so the simplest way of verification is to run some test against some cluster:
make testsuite/tests/singlecluster/gateway/test_basic.py::test_gateway_readiness
- it should pass with 'istio' being the name for GatewayClass used in Gateway CR that got created
Then change the 'openshift-default' in code to …
=> Get GatewayClass name from cluster

testsuite/gateway/envoy/jwt_plain_identity.py, testsuite/tests/singlecluster/authorino/identity/plain/test_jwt_plain_identity.py
This PR addresses part of issue #673. It tests two cases of authentication in Envoy using the Envoy JWT authentication filter. The first case is when the user has a role assigned, and the second case is when the user does not have a role assigned.
=> JWT plain identity test

testsuite/kuadrant/policy/__init__.py, testsuite/kuadrant/policy/rate_limit.py, testsuite/tests/singlecluster/authorino/identity/anonymous/test_anonymous_identity.py
Added check function that will assert the generation has been incremented before confirming it the policy enforcement.
=> Added more resilience on update policies.

testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py
Issue described in #696. This fix aims to help avoid inconsistent test failures when DNS records take time to propagate, especially on Azure.
Some `change_targetref` tests run before DNS is fully ready. Even though the DNSPolicy was created successfully, its status showed:
```
type: Enforced
status: 'False'
message: 'DNSPolicy has encountered some issues: policy is not enforced on any DNSRecord: not a single DNSRecord is ready'
```
With recordConditions stuck in:
```
reason: AwaitingValidation
status: 'False'
type: Ready
```
This caused test traffic to hit unresolved hostnames and fail with DNS-related errors (nodename nor servname provided).
* Refactored DNS readiness logic into the `dns_policy2` fixture:
* Waits for `recordConditions` to report `"Ready"` with `status=True`
* Waits until …
=> Update change_targetref tests to fix azure DNS issue

testsuite/kubernetes/client.py, testsuite/tests/singlecluster/gateway/reconciliation/test_invalid_issuer_reference.py
https://github.com/Kuadrant/kuadrant-operator/pull/1393 changed message returned if an invalid issuer kind has been set (like 'Gateway' in this test). Validation also was moved to the object creation
`pytest /home/averevki/work/testsuite/testsuite/tests/singlecluster/gateway/reconciliation/test_invalid_issuer_reference.py`
=> Fix invalid issuer test

testsuite/kubernetes/__init__.py, testsuite/tests/multicluster/load_balanced/test_change_default_geo.py, testsuite/tests/multicluster/load_balanced/test_change_strategy.py, testsuite/tests/multicluster/load_balanced/test_unsupported_geocode.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py
Also removed related asserts from dns tests, leftover from https://github.com/Kuadrant/testsuite/pull/654
`make dnstls`, `make testsuite/tests/singlecluster/gateway/reconciliation/change_targetref`
=> Improve apply() logic

testsuite/gateway/envoy/config.py, testsuite/gateway/envoy/jwt_plain_identity.py, testsuite/gateway/envoy/route.py, testsuite/mockserver.py, testsuite/tests/singlecluster/authorino/identity/plain/conftest.py, testsuite/tests/singlecluster/authorino/identity/plain/test_jwt_plain_identity.py, testsuite/tests/singlecluster/authorino/identity/plain/test_jwt_user_story.py
This PR implements the user story from issue #689 into the testsuite.
As a user you can access from anywhere if you have a realm role assigned. But if user does not have assigned realm role than the user can access only from allowed path parameter "/anythig/SK/" or when accessing through "/anything/global" path parameter that does not trigger external authorization by Envoy.
=> Add JWT test implementing user story from user-guides

testsuite/tests/singlecluster/authorino/identity/plain/conftest.py, testsuite/tests/singlecluster/authorino/identity/plain/test_jwt_plain_identity.py, testsuite/tests/singlecluster/authorino/identity/plain/test_jwt_user_story.py
This PR moves a fixture from conftest.py directly into the test file to investigate and resolve an issue with the response status code 500.
Changes:
- Relocated the fixture closer to the test that uses it.
- No changes to test logic, only fixture location.
Purpose:
- To determine if the response status code issue is related to the fixture being defined globally in conftest.py.
=> Move fixture closer to test to check response status code issue

config/settings.yaml
Update of default images used by testsuite in `config/settings.yaml`
- all three are multiarch manifests now
- envoy updated to v1.35
Make sure you are not overriding these in `config/settings.local.yaml`, then execute both kuadrant tests and authorino standalone tests against amd64 (standard architecture) cluster:
`flags="-vvv" make test`
`flags="-vvv --standalone" make authorino-standalone`
However, it is probably ok to run just one test of each instead of whole test suite.
You can also pull all the images for ARM64 to validate that these are indeed multiarch manifests:
```
podman pull --platform linux/arm64 quay.io/rhn_support_azgabur/httpbin:latest
podman pull --platform linux/arm64 quay.io/rhn_support_azgabur/mockserver:latest
podman pull --platform linux/arm64 …
```
=> Update of default images

testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_authpolicy_target_ref.py, testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_dnspolicy_target_ref.py
change_targetref DNSPolicy test is failing almost every night for the last few weeks (and sometimes rate limit tests too). Adding a refresh has made these tests stable again.
**Summary of changes:** 
* Added`policy.refresh()` before updating `targetRef`
* Switched DNSPolicy and AuthPolicy test to use `wait_until` for gateway assertions for consistency with the other two tests
=> Update change_target_ref function and improve consistency

.github/workflows/test-pr.yml
This PR adds a GitHub Actions workflow that enables running testsuite commands on pull requests through issue comments. The workflow provides a convenient way to test PRs without requiring manual setup of test environments.
- **Added `.github/workflows/test-pr.yml`**: Complete GitHub Actions workflow for PR testing
- Triggers on issue comments starting with `/make <target>`
- Validates allowed make targets against predefined list
- Sets up complete KIND cluster with required infrastructure
- Installs and configures all dependencies (MetalLB, Gateway API, cert-manager, Sail Operator, Istio, Kuadrant)
- Creates necessary namespaces and secrets for testing
- Runs the specified make target and reports results back to the PR
Eye review is sufficient for this PR. The workflow is self-contained …
=> Add GitHub Action to run testsuite on PRs

scale_test/control-plane-config.yaml, scale_test/max-gateway-listeners/templates/httpbin-deployment.yaml, scale_test/templates/httpbin-deployment.yaml
Cleanup condition fix and httpbin image update in scale test.
Eye review probably suffice. The cleanup condition is relatively trivial and the httpbin image had been validated as part of review of https://github.com/Kuadrant/testsuite/pull/729
If you want to be thorough you can run the scale test as described in scale-test/control-plane.md several times with various values for SKIP_CLEANUP env var:
- have it undefined (`unset SKIP_CLEANUP`) -> error saying that you need to define it
- have it empty (`SKIP_CLEANUP= # empty`) -> success with cleanup
- have it set to true (`SKIP_CLEANUP=true`) -> success without cleanup
- have it set to false (`SKIP_CLEANUP=false`) -> success with cleanup
=> Scale test: cleanup condition fix and httpbin image update

.github/workflows/test-pr.yml
A branch hasn't been picked automatically by the checkout action because the workflow is triggered from PR event. Fixing it by acquiring the PR branch from github API
=> Fix CI branch checkout on PR event

testsuite/kuadrantctl.py, testsuite/tests/kuadrantctl/cli/test_basic_commands.py, testsuite/tests/kuadrantctl/conftest.py
Fix kuadrantctl tests. Added new test for shell completions.
Closes #514 
Don't need to verify, it generates policies with old manifests. kuadrantctl is not being developed or updated currently. 
Basic commands and route generation tests still work though.
=> Fix kuadrantctl tests

testsuite/kuadrant/extensions/telemetry_policy.py
Adds TelemetryPolicy class into testsuite that allows configuring telemetry metrics labels on Gateway resources.
Known Issues
- TODO: Delete wait_for_ready(self) method when TelemetryPolicy status is fixed.
=> Add class for TelemetryPolicy

testsuite/spicedb/spicedb.py
Remove jitter and adjust retry interval
- Add `jitter=None` to ensure consistent wait times between retries
- Update interval from 3s to 5s and max_tries from 5 to 3
=> Fix backoff in spicedb

testsuite/prometheus.py, testsuite/tests/multicluster/coredns/two_clusters/metrics/conftest.py, testsuite/tests/multicluster/coredns/two_clusters/metrics/test_metrics.py
Add metrics testing for CoreDNS multicluster DNS operations in the Kuadrant testsuite.
Closes #772
- **New metrics tests:**
- Authoritative DNS record metrics verification (dns_provider_record_ready, dns_provider_write_counter, dns_provider_authoritative_record_spec_info)
- Delegating DNS record metrics testing across primary/secondary clusters
- Multi-cluster count metrics validation (dns_provider_active_multi_cluster_count)
- Remote DNS records metrics testing (dns_provider_remote_records, dns_provider_remote_record_reconcile_count)
```bash
flags=-n1 make testsuite/tests/multicluster/coredns/two_clusters/metrics
```
You would need a 1 primary and 1 secondary cluster for this test. Primaries, at the moment of writing, are kua-419 and kua-419. Secondray can be whatever cluster with …
=> Add CoreDNS metrics tests

Makefile
Disruptive tests shouldn't run together with multicluster tests
=> Remove disruptive from multicluster make target
