Kuadrant/testsuite

testsuite/openshift/httpbin.py
testsuite/resources/httpbin.yaml

Change Httpbin to Deployment

---

testsuite/tests/kuadrant/authorino/identity/rhsso/multiple_hosts/conftest.py
testsuite/tests/kuadrant/authorino/identity/rhsso/multiple_hosts/test_multiple_hosts.py
testsuite/tests/kuadrant/authorino/identity/rhsso/multiple_hosts/test_remove_host.py

Also clean ups multiple host test.
Depends on #38 
Closes #35

Add remove host test

---

config/settings.local.yaml.tpl
testsuite/tests/conftest.py
testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py
testsuite/tests/kuadrant/authorino/operator/clusterwide/test_clusterwide.py
testsuite/tests/kuadrant/authorino/operator/conftest.py

Enable running Authorino in cluster-wide mode and add a simple test for it

Add Clusterwide support

---

testsuite/tests/kuadrant/authorino/conftest.py
testsuite/tests/kuadrant/authorino/operator/tls/conftest.py
testsuite/tests/kuadrant/conftest.py

- Autouse fixture which handles commiting authorization and all of the important stuff
- Completes #36

Introduce commit fixture

---

testsuite/httpx/auth.py
testsuite/tests/kuadrant/authorino/identity/api_key/conftest.py
testsuite/tests/kuadrant/authorino/identity/api_key/test_match_expression.py
testsuite/tests/kuadrant/authorino/identity/api_key/test_match_label.py

Add Httpx custom Auth class for API Key Authorization and update tests accordingly.

Add API Key Auth class

---

Dockerfile
README.md

/run should have better permissions when binding from outside

Change KUBECONFIG and Secrets location to /run in Dockefile

---

testsuite/openshift/client.py
testsuite/openshift/httpbin.py
testsuite/openshift/types/__init__.py
testsuite/openshift/types/routes.py
testsuite/openshift/types/secrets.py

Copied from the 3scale testsuite.

Add Routes and Secrets objects

---

testsuite/objects/__init__.py
testsuite/openshift/objects/auth_config.py
testsuite/tests/kuadrant/authorino/operator/clusterwide/test_wildcard_collision.py
testsuite/tests/kuadrant/authorino/operator/conftest.py
testsuite/tests/kuadrant/authorino/operator/test_wildcard.py
testsuite/tests/kuadrant/authorino/operator/tls/conftest.py

#49 needs to be merged first
Closes #22

Add tests for wildcard hosts

---

testsuite/objects/__init__.py
testsuite/openshift/objects/auth_config.py
testsuite/rhsso/objects.py
testsuite/tests/kuadrant/authorino/identity/rhsso/test_rhsso_roles.py

Add role authentication test

---

testsuite/rhsso/objects.py

Newer Keycloak versions use `<url>/realm/realm-name` instead of previously used `<url>/auth/realm/realm-name`. RHSSO is still based on an older Keycloak, so we had a workaround for it to work. That workaround meant that newer Keycloak would not work.

Fix running with newer Keycloak versions

---

testsuite/tests/kuadrant/authorino/identity/auth/test_multiple_auth_identities.py

Add tests for multiple auth identities (RHSSO + Auth0).
#60 needs to be merged first
Closes #14

Multiple auth identities

---

testsuite/openshift/objects/auth_config.py
testsuite/openshift/types/routes.py
testsuite/tests/kuadrant/authorino/operator/http/conftest.py
testsuite/tests/kuadrant/authorino/operator/http/test_raw_http.py

closes https://github.com/Kuadrant/testsuite/issues/9

Add raw http test with response with adding extra header

---

testsuite/tests/kuadrant/authorino/operator/http/conftest.py

- unnecessary rhsso_service_info dependency

Fix http test

---

pytest.ini
testsuite/tests/kuadrant/authorino/operator/sharding/test_preexisting_auth.py

Add pytest mark for issue so we can mark tests with issue they are written for.
#82 needs to be merged first
Closes #86

Add pytest mark for issue

---

testsuite/tests/kuadrant/authorino/response/conftest.py
testsuite/tests/kuadrant/authorino/response/test_auth_json.py
testsuite/tests/kuadrant/authorino/response/test_multiple_responses.py
testsuite/tests/kuadrant/authorino/response/test_simple_response.py
testsuite/tests/kuadrant/authorino/response/test_wrapper_key.py

A few simple test cases. If you have any more ideas, let me know.

Add json response tests

---

testsuite/objects/__init__.py
testsuite/openshift/objects/auth_config.py
testsuite/tests/kuadrant/authorino/test_redirect.py

Add redirect test

---

testsuite/objects/__init__.py
testsuite/openshift/objects/auth_config.py
testsuite/tests/kuadrant/authorino/identity/test_anonymous_identity.py

Add test for anonymous identity

---

testsuite/config/__init__.py

Fix dynaconf_loaders priority

---

testsuite/mockserver.py
testsuite/objects/__init__.py
testsuite/openshift/objects/auth_config.py
testsuite/tests/kuadrant/authorino/metadata/test_http.py
testsuite/utils.py

Based on documentation: https://github.com/Kuadrant/authorino/blob/main/docs/features.md#oidc-userinfo-metadatauserinfo
For issue: https://github.com/Kuadrant/testsuite/issues/6

Tests for External auth metadata features

---

testsuite/oidc/rhsso/__init__.py
testsuite/oidc/rhsso/objects.py
testsuite/tests/kuadrant/authorino/identity/rhsso/test_rhsso_context.py
testsuite/tests/kuadrant/authorino/identity/rhsso/test_rhsso_roles.py

QoL improvement to RHSSO user manipulation

Add User RHSSO object

---

testsuite/certificates/__init__.py
testsuite/objects/__init__.py
testsuite/openshift/client.py
testsuite/openshift/objects/auth_config.py
testsuite/tests/kuadrant/authorino/operator/tls/conftest.py
testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_identity.py
testsuite/utils.py

Add a basic mTLS identity tests

---

testsuite/oidc/rhsso/objects.py
testsuite/tests/kuadrant/authorino/metadata/test_user_info.py

- Make it work with #131 
- Use two users instead of modifying one -> RHSSO is session scoped and other test could rely on email which we currently change

Fix user info test

---

testsuite/objects/__init__.py
testsuite/objects/sections.py
testsuite/openshift/objects/auth_config/sections.py

Add support for Common Features

---

testsuite/objects/sections.py
testsuite/openshift/objects/auth_config/sections.py
testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py

I added common_features to all methods however I didn't remove existing alternatives, this PR fixes it.
Also includes minor improvements to the webhook test

Use common_features in all methods

---

testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py
testsuite/tests/kuadrant/authorino/operator/tls/conftest.py

Fix clusterwide tests on Authorino

---

Dockerfile

* Add CFSSL (Not sure why it wasn't there before)
* Add __init__.py to resources
* Switch to CentOS 9

Dockefile updates

---

testsuite/openshift/objects/gateway_api/__init__.py
testsuite/tests/kuadrant/authorino/conftest.py
testsuite/tests/kuadrant/conftest.py
testsuite/tests/kuadrant/reconciliation/conftest.py
testsuite/tests/kuadrant/reconciliation/test_httproute_hosts.py
testsuite/tests/kuadrant/reconciliation/test_httproute_matches.py

Add tests for HTTPRoute reconciliation

---

testsuite/tests/kuadrant/reconciliation/conftest.py

Thanks, @averevki, for noticing it.

Fix Kuadrant skip in reconciliation tests

---

testsuite/openshift/client.py
testsuite/openshift/objects/auth_config/__init__.py
testsuite/openshift/objects/auth_config/auth_policy.py
testsuite/openshift/objects/gateway_api/__init__.py

Thanks again @averevki, for suggestion :D

Update how labels are handles in OpenshiftObjects

---

testsuite/tests/conftest.py

- If Kuadrant is enabled, it will fail if it cannot find it.

No fallback for Kuadrant

---

testsuite/tests/kuadrant/authorino/response/test_wrapper_key.py

Remove / from test_wrapper_key

---

Dockerfile
Makefile

- Only if there is no other env installed
- I am terrible at shell

Add back poetry management to Makefile

---

testsuite/openshift/objects/rate_limit.py
testsuite/tests/kuadrant/reconciliation/conftest.py

Stability fixes

---

testsuite/mockserver.py

Use ApyProxy for Mockserver

---

testsuite/openshift/objects/rate_limit.py

Changes based on https://github.com/Kuadrant/kuadrant-operator/issues/133

Remove unnecessary fields for RateLimitPolicy

---

Makefile

Run poetry install when force has any value

---

testsuite/tests/kuadrant/authorino/priority/conftest.py
testsuite/tests/kuadrant/authorino/priority/test_dependency.py
testsuite/tests/kuadrant/authorino/priority/test_sequence_anonymous.py
testsuite/tests/kuadrant/authorino/priority/test_sequence_api_key.py

Add tests for Common feature - Priority

---

testsuite/objects/__init__.py
testsuite/openshift/objects/auth_config/__init__.py
testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_authorization_condition.py
testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_identity_condition.py
testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_metadata_condition.py
testsuite/tests/kuadrant/authorino/conditions/section_conditions/test_response_condition.py
testsuite/tests/kuadrant/authorino/conditions/test_top_level_condition.py

Add tests for Common feature - Conditions

---

testsuite/tests/conftest.py

Results in `Kuadrant/testsuite#189` naming scheme in HTML file.

Add pytest.mark.issue

---

testsuite/tests/kuadrant/authorino/response/test_base64.py

Test for this fix: https://github.com/Kuadrant/authorino/pull/401

Add base64 tests

---

testsuite/openshift/objects/auth_config/sections.py

It was missing for some reason

Fix add_simple common features handling

---

.github/workflows/acceptance.yml
Dockerfile
README.md
pyproject.toml

Bump python to 3.11 in acceptance.yml

---

testsuite/openshift/objects/gateway_api/__init__.py

Fix route cleanup for Gateway class

---

testsuite/tests/kuadrant/authorino/identity/api_key/test_auth_credentials.py

Fix wrong credentials parameters that were missed in https://github.com/Kuadrant/testsuite/pull/248 and `if` expansion as in  https://github.com/Kuadrant/testsuite/pull/246

Fix wrong credentials param api_key/test_auth_credentials.py

---

testsuite/openshift/objects/gateway_api/gateway.py

Fix TLSPolicy secret cleanup if secret does not exist

Fix mgc tls secret deletion

---

pyproject.toml

- Update the minimal version for python-keycloak
It got merged & release far quicker than I expected :D

Remove setuptools from pyproject.toml

---

testsuite/config/openshift_loader.py

- Sadly it doesn't really work

Revert load() kwargs

---

testsuite/tests/kuadrant/authorino/wristband/conftest.py
testsuite/tests/kuadrant/authorino/wristband/test_wristband.py

- Use standard client in test methods
- Improve fixture naming

Enhance wristband test

---

.github/workflows/promote_to_latest.yml

It needs to be multiline command

Fix promote_to_latest.yml

---

pyproject.toml
testsuite/gateway/envoy/__init__.py
testsuite/gateway/gateway_api/gateway.py
testsuite/openshift/__init__.py
testsuite/openshift/authorino.py
testsuite/openshift/client.py
testsuite/openshift/deployment.py
testsuite/policy/authorization/auth_config.py
testsuite/policy/dns_policy.py
testsuite/policy/rate_limit_policy.py
testsuite/tests/kuadrant/authorino/metrics/conftest.py
testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py
testsuite/tests/mgc/conftest.py

- Only notable change is package naming (finally)

Update to openshift_client 2.0

---

testsuite/tests/kuadrant/test_rate_limit_anonymous.py

Closes #188
Adding test that rate limits unauthenticated users

Add test for rate limiting anonymous users

---

testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_attributes.py
testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_identity.py
testsuite/tests/kuadrant/authorino/operator/tls/mtls/test_mtls_trust_chain.py

Missed in https://github.com/Kuadrant/testsuite/pull/288

Add pytest marks to mtls tests

---

testsuite/tests/kuadrant/gateway/conftest.py
testsuite/tests/kuadrant/gateway/test_basic.py
testsuite/tests/kuadrant/reconciliation/conftest.py
testsuite/tests/kuadrant/test_rate_limit_anonymous.py

* Adds also marks to a few tests that didn't have them

Fix redundant kuadrant fixture

---

README.md

Reformat of example AuthConfig in readme to AuthConfig v2

Refactor README.md to AuthConfig v2

---

config/settings.local.yaml.tpl
testsuite/config/__init__.py
testsuite/config/tools.py
testsuite/httpx/__init__.py
testsuite/openshift/authorino.py
testsuite/openshift/client.py
testsuite/tests/conftest.py
testsuite/tests/kuadrant/authorino/tracing/conftest.py
testsuite/tests/kuadrant/authorino/tracing/test_tracing.py
testsuite/tests/kuadrant/authorino/tracing/test_tracing_tags.py
testsuite/tracing.py

Authorino request tracing tests
- Add tracing client for the traces management
- Add test for trace collection
- Add test for custom trace tags
closes #189

Test authorino tracing

---

testsuite/tests/kuadrant/authorino/identity/plain/test_plain_identity.py
testsuite/utils.py

Authorino Plain Identity test
- Add simple test for Plain Identity
closes https://github.com/Kuadrant/testsuite/issues/111

Add plain identity test

---

testsuite/tests/mgc/conftest.py

Fix MGC fixtures scope

---

testsuite/tests/kuadrant/authorino/dinosaur/test_dinosaur.py

from: https://github.com/Kuadrant/testsuite/issues/378
to: https://github.com/Kuadrant/kuadrant-operator/issues/566

Change issue link to kuadrant-operator repo

---

testsuite/policy/authorization/auth_policy.py
testsuite/policy/rate_limit_policy.py
testsuite/utils.py

* For AuthPolicy and RateLimitPolicy

Use Enforced condition for ready check

---

testsuite/policy/rate_limit_policy.py

It seems like it still needs a bit of sleep

Reintroduce sleep into RLP wait

---

testsuite/openshift/metrics/prometheus.py

ref: https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcnow

Fix timezone aware time deprecation warning

---

testsuite/tests/kuadrant/authorino/operator/tls/conftest.py

* Fixes failing `make authorino-standalone`

De-scope exposer fixture for TLS tests

---

Makefile
testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py

* Add context to webhook.delete()
* Add `ValidatingWebhookConfiguration` to `make clean`

Improve test_webhook

---

testsuite/httpx/__init__.py

Should help with stability in nightly environment

Add timed out to backoff errors

---

testsuite/tests/kuadrant/authorino/operator/sharding/test_preexisting_auth.py

Add wait to test_preexisting_auth

---

Makefile
pyproject.toml

* Use `package-mode=false`
* No need to use `--no-root`
* Requires poetry 1.8
* Update description and email

pyproject.toml improvements

---

testsuite/httpx/__init__.py

I sometimes encounter also this error

Add additional DNS error to backoff

---

testsuite/tests/kuadrant/authorino/operator/sharding/test_preexisting_auth.py

It should help to debug issue in nightlies

Add custom assert to preexisting_auth to see more details

---

testsuite/oidc/auth0.py
testsuite/tests/conftest.py
testsuite/tests/kuadrant/authorino/conftest.py
testsuite/tests/kuadrant/authorino/metrics/conftest.py
testsuite/tests/kuadrant/authorino/operator/clusterwide/conftest.py
testsuite/tests/kuadrant/authorino/operator/raw_http/conftest.py
testsuite/tests/kuadrant/authorino/operator/raw_http/test_raw_http.py
testsuite/tests/kuadrant/authorino/operator/sharding/conftest.py
testsuite/tests/kuadrant/authorino/operator/tls/test_webhook.py
testsuite/tests/kuadrant/authorino/wristband/conftest.py
testsuite/tests/kuadrant/conftest.py

* Also includes a slight fix for using `testconfig` instead of `settings`

Remove global unused-argument disables

---

Makefile
pyproject.toml
testsuite/tests/kuadrant/gateway/reconciliation/test_affected_by.py
testsuite/tests/kuadrant/gateway/reconciliation/test_gw_doesnt_exist.py
testsuite/tests/kuadrant/gateway/reconciliation/test_invalid_issuer_reference.py
testsuite/tests/kuadrant/gateway/reconciliation/test_same_target.py
testsuite/tests/kuadrant/gateway/test_dns.py
testsuite/tests/kuadrant/gateway/test_external_ca.py
testsuite/tests/kuadrant/gateway/tlspolicy/test_cert_parameters.py

Add dnstls target

---

testsuite/gateway/exposers.py
testsuite/httpx/__init__.py
testsuite/tests/kuadrant/authorino/operator/tls/conftest.py

* If you force SNI hostname all TLS tests work

Enable TLS tests on Kind/Kubernetes

---

testsuite/policy/__init__.py
testsuite/tests/kuadrant/gateway/reconciliation/test_gw_doesnt_exist.py
testsuite/tests/kuadrant/gateway/reconciliation/test_invalid_issuer_reference.py
testsuite/tests/kuadrant/gateway/reconciliation/test_same_target.py
testsuite/utils.py

There is still dependence on `check_condition` from utils. That method is used in route and gateway and moving it here might cause dependency cycle

Move has_condition to policy module

---

testsuite/policy/tls_policy.py
testsuite/tests/kuadrant/gateway/test_external_ca.py

Fix external ca test

---

testsuite/tests/kuadrant/conftest.py

* Fixes current nightly failures

Remove committed from conftest

---

Makefile

- I do not think we ever used it

Remove all-is-package check

---

testsuite/tests/multicluster/conftest.py

Waiting is now done in TLSPolicy itself

Remove sleep from multicluster

---

.github/workflows/project.yml

* Always adds PR to the board, even if they are not linked to an issue
* Moves related issue as well
As with every action, we will see if it works only after we merge it :) So expect a few fixes or possibly a complete removal

Add action to move PR to "In Review" when opened

---

README.md
config/settings.local.yaml.tpl
config/settings.yaml
testsuite/config/__init__.py
testsuite/gateway/gateway_api/hostname.py
testsuite/kuadrant/policy/dns.py
testsuite/tests/conftest.py
testsuite/tests/multicluster/conftest.py
testsuite/tests/singlecluster/gateway/conftest.py
testsuite/tests/singlecluster/gateway/reconciliation/__init__.py
testsuite/tests/singlecluster/gateway/reconciliation/test_gw_doesnt_exist.py
testsuite/tests/singlecluster/gateway/reconciliation/test_same_target.py

Refactor due to ManagedZone removal

---

testsuite/gateway/gateway_api/hostname.py
testsuite/tests/singlecluster/gateway/dnspolicy/test_dnspolicy_removal.py

Part of the https://github.com/Kuadrant/testsuite/issues/531

Add dnspolicy deletion test

---

pyproject.toml

Disable too-many-positional arguments from pylint

---

testsuite/tests/multicluster/load_balanced/test_unsupported_geocode.py

see https://github.com/Kuadrant/testsuite/pull/516#discussion_r1738855863

Improve assert on unsupported geo test

---

config/settings.local.yaml.tpl
testsuite/config/__init__.py
testsuite/tests/multicluster/load_balanced/conftest.py
testsuite/tests/multicluster/load_balanced/test_change_default_geo.py
testsuite/tests/multicluster/load_balanced/test_change_strategy.py
testsuite/tests/multicluster/load_balanced/test_load_balanced_geo.py

- Add DNSPolicy modification tests
- Test for changing default geo-code
- Test for changing load-balancing strategy
- Improve basic geo load-balancing test
Closes #531

DNSPolicy modification tests

---

testsuite/kuadrant/policy/dns.py
testsuite/kuadrant/policy/tls.py

Merge after merging of https://github.com/Kuadrant/kuadrant-operator/pull/973
There should not be any other changes

Move DNS/TLSPolicy to v1

---

pyproject.toml

https://github.com/Kuadrant/testsuite/pull/589#issuecomment-2524147405
So other PR tests pass. In the future the testsuite can be refactored so new version can be used

Temp freeze of httpx library

---

testsuite/tests/singlecluster/authorino/identity/subject_access_review/test_subject_access_review.py
testsuite/tests/singlecluster/conftest.py
testsuite/tests/singlecluster/limitador/route/conftest.py

Causing other PRs to fail see https://github.com/Kuadrant/testsuite/pull/615

fix: formatting

---

testsuite/tests/singlecluster/authorino/response/test_deny_with.py

Link moved to a separate issue https://github.com/Kuadrant/testsuite/issues/647

Change to valid return codes in deny_with tests

---

.github/pull_request_template.md
testsuite/tests/singlecluster/identical_hostnames/rlp/test_rlp_on_routes.py
testsuite/tests/singlecluster/overrides/test_basic_auth.py
testsuite/tests/singlecluster/overrides/test_basic_rate_limit.py

Small fixes in docstrings. New line at the end of the PR Template removed as well.
This PR was mostly done to see how the new PR Template works. It works OK imo (apart from that newline fixed in this PR)

Small fixes in docstrings

---

testsuite/tests/singlecluster/authorino/operator/tracing/test_tracing.py
testsuite/tests/singlecluster/authorino/operator/tracing/test_tracing_tags.py

Marked tracing tests with xfail and attached the related issue https://github.com/Kuadrant/testsuite/issues/659

Attached issue and xfailed tracing tests

---

testsuite/tests/singlecluster/authorino/operator/tracing/test_tracing.py
testsuite/tests/singlecluster/authorino/operator/tracing/test_tracing_tags.py

Removed xfail mark from tracing tests

---

Makefile
testsuite/config/__init__.py
testsuite/custom_metrics_apiserver/client.py
testsuite/gateway/gateway_api/gateway.py
testsuite/kubernetes/client.py
testsuite/kubernetes/deployment.py
testsuite/kubernetes/horizontal_pod_autoscaler.py
testsuite/kubernetes/monitoring/__init__.py
testsuite/kubernetes/service.py
testsuite/tests/singlecluster/gateway/scaling/conftest.py
testsuite/tests/singlecluster/gateway/scaling/test_auto_scale_gateway.py
testsuite/tests/singlecluster/gateway/scaling/test_manual_scale_gateway.py

This PR aims to fix issue: #559

Scale gateway tests.

---

testsuite/tests/multicluster/load_balanced/conftest.py

Fix load_balancing parameter that is broken since https://github.com/Kuadrant/testsuite/pull/764 was merged

Fix load balancing parameter
